package com.skf.management.mapper;

import com.skf.management.model.ComponentModel;
import com.skf.management.model.ComponentModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ComponentModelMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf_cmpt
	 * @mbg.generated  Tue Jun 05 15:12:19 CST 2018
	 */
	long countByExample(ComponentModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf_cmpt
	 * @mbg.generated  Tue Jun 05 15:12:19 CST 2018
	 */
	int deleteByExample(ComponentModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf_cmpt
	 * @mbg.generated  Tue Jun 05 15:12:19 CST 2018
	 */
	int deleteByPrimaryKey(String code);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf_cmpt
	 * @mbg.generated  Tue Jun 05 15:12:19 CST 2018
	 */
	int insert(ComponentModel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf_cmpt
	 * @mbg.generated  Tue Jun 05 15:12:19 CST 2018
	 */
	int insertSelective(ComponentModel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf_cmpt
	 * @mbg.generated  Tue Jun 05 15:12:19 CST 2018
	 */
	List<ComponentModel> selectByExample(ComponentModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf_cmpt
	 * @mbg.generated  Tue Jun 05 15:12:19 CST 2018
	 */
	ComponentModel selectByPrimaryKey(String code);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf_cmpt
	 * @mbg.generated  Tue Jun 05 15:12:19 CST 2018
	 */
	int updateByExampleSelective(@Param("record") ComponentModel record,
			@Param("example") ComponentModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf_cmpt
	 * @mbg.generated  Tue Jun 05 15:12:19 CST 2018
	 */
	int updateByExample(@Param("record") ComponentModel record, @Param("example") ComponentModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf_cmpt
	 * @mbg.generated  Tue Jun 05 15:12:19 CST 2018
	 */
	int updateByPrimaryKeySelective(ComponentModel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf_cmpt
	 * @mbg.generated  Tue Jun 05 15:12:19 CST 2018
	 */
	int updateByPrimaryKey(ComponentModel record);
}