package com.skf.management.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.skf.management.entity.UserCustomerEntity;
import com.skf.management.model.UserCustomerModelExample;
import com.skf.management.model.UserCustomerModelKey;

public interface UserCustomerModelMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf_usr_cstm
	 * @mbg.generated  Fri Jun 15 17:49:01 CST 2018
	 */
	long countByExample(UserCustomerModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf_usr_cstm
	 * @mbg.generated  Fri Jun 15 17:49:01 CST 2018
	 */
	int deleteByExample(UserCustomerModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf_usr_cstm
	 * @mbg.generated  Fri Jun 15 17:49:01 CST 2018
	 */
	int deleteByPrimaryKey(UserCustomerModelKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf_usr_cstm
	 * @mbg.generated  Fri Jun 15 17:49:01 CST 2018
	 */
	int insert(UserCustomerModelKey record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf_usr_cstm
	 * @mbg.generated  Fri Jun 15 17:49:01 CST 2018
	 */
	int insertSelective(UserCustomerModelKey record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf_usr_cstm
	 * @mbg.generated  Fri Jun 15 17:49:01 CST 2018
	 */
	List<UserCustomerModelKey> selectByExample(UserCustomerModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf_usr_cstm
	 * @mbg.generated  Fri Jun 15 17:49:01 CST 2018
	 */
	int updateByExampleSelective(@Param("record") UserCustomerModelKey record,
			@Param("example") UserCustomerModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf_usr_cstm
	 * @mbg.generated  Fri Jun 15 17:49:01 CST 2018
	 */
	int updateByExample(@Param("record") UserCustomerModelKey record,
			@Param("example") UserCustomerModelExample example);

	/**
	 * Add By Jamie 20180608
	 * @param userCode
	 * @return List<UserCustomerEntity>
	 */
	List<UserCustomerEntity> selectByUserCode(String userCode);
}