package com.skf.management.sqlservermapper;

import com.skf.management.model.DboBearingModel;
import com.skf.management.model.DboBearingModelExample;
import com.skf.management.model.DboBearingModelKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DboBearingModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Bearing
     *
     * @mbg.generated Mon Jun 11 17:10:37 CST 2018
     */
    long countByExample(DboBearingModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Bearing
     *
     * @mbg.generated Mon Jun 11 17:10:37 CST 2018
     */
    int deleteByExample(DboBearingModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Bearing
     *
     * @mbg.generated Mon Jun 11 17:10:37 CST 2018
     */
    int deleteByPrimaryKey(DboBearingModelKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Bearing
     *
     * @mbg.generated Mon Jun 11 17:10:37 CST 2018
     */
    int insert(DboBearingModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Bearing
     *
     * @mbg.generated Mon Jun 11 17:10:37 CST 2018
     */
    int insertSelective(DboBearingModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Bearing
     *
     * @mbg.generated Mon Jun 11 17:10:37 CST 2018
     */
    List<DboBearingModel> selectByExampleWithBLOBs(DboBearingModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Bearing
     *
     * @mbg.generated Mon Jun 11 17:10:37 CST 2018
     */
    List<DboBearingModel> selectByExample(DboBearingModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Bearing
     *
     * @mbg.generated Mon Jun 11 17:10:37 CST 2018
     */
    DboBearingModel selectByPrimaryKey(DboBearingModelKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Bearing
     *
     * @mbg.generated Mon Jun 11 17:10:37 CST 2018
     */
    int updateByExampleSelective(@Param("record") DboBearingModel record, @Param("example") DboBearingModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Bearing
     *
     * @mbg.generated Mon Jun 11 17:10:37 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") DboBearingModel record, @Param("example") DboBearingModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Bearing
     *
     * @mbg.generated Mon Jun 11 17:10:37 CST 2018
     */
    int updateByExample(@Param("record") DboBearingModel record, @Param("example") DboBearingModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Bearing
     *
     * @mbg.generated Mon Jun 11 17:10:37 CST 2018
     */
    int updateByPrimaryKeySelective(DboBearingModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Bearing
     *
     * @mbg.generated Mon Jun 11 17:10:37 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(DboBearingModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Bearing
     *
     * @mbg.generated Mon Jun 11 17:10:37 CST 2018
     */
    int updateByPrimaryKey(DboBearingModel record);
}