package com.skf.management.sqlservermapper;

import com.skf.management.model.NodeModel;
import com.skf.management.model.NodeModelExample;
import com.skf.management.model.NodeModelWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NodeModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Node
     *
     * @mbg.generated Tue Jun 05 10:28:23 CST 2018
     */
    long countByExample(NodeModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Node
     *
     * @mbg.generated Tue Jun 05 10:28:23 CST 2018
     */
    int deleteByExample(NodeModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Node
     *
     * @mbg.generated Tue Jun 05 10:28:23 CST 2018
     */
    int deleteByPrimaryKey(Integer nodeID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Node
     *
     * @mbg.generated Tue Jun 05 10:28:23 CST 2018
     */
    int insert(NodeModelWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Node
     *
     * @mbg.generated Tue Jun 05 10:28:23 CST 2018
     */
    int insertSelective(NodeModelWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Node
     *
     * @mbg.generated Tue Jun 05 10:28:23 CST 2018
     */
    List<NodeModelWithBLOBs> selectByExampleWithBLOBs(NodeModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Node
     *
     * @mbg.generated Tue Jun 05 10:28:23 CST 2018
     */
    List<NodeModel> selectByExample(NodeModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Node
     *
     * @mbg.generated Tue Jun 05 10:28:23 CST 2018
     */
    NodeModelWithBLOBs selectByPrimaryKey(Integer nodeID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Node
     *
     * @mbg.generated Tue Jun 05 10:28:23 CST 2018
     */
    int updateByExampleSelective(@Param("record") NodeModelWithBLOBs record, @Param("example") NodeModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Node
     *
     * @mbg.generated Tue Jun 05 10:28:23 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") NodeModelWithBLOBs record, @Param("example") NodeModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Node
     *
     * @mbg.generated Tue Jun 05 10:28:23 CST 2018
     */
    int updateByExample(@Param("record") NodeModel record, @Param("example") NodeModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Node
     *
     * @mbg.generated Tue Jun 05 10:28:23 CST 2018
     */
    int updateByPrimaryKeySelective(NodeModelWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Node
     *
     * @mbg.generated Tue Jun 05 10:28:23 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(NodeModelWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Node
     *
     * @mbg.generated Tue Jun 05 10:28:23 CST 2018
     */
    int updateByPrimaryKey(NodeModel record);
}