package com.skf.management.model;

import java.util.Date;

public class AlarmModel extends AlarmModelKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKF_ALRM.ALRM_TIME
	 * @mbg.generated  Fri Jun 15 18:04:35 CST 2018
	 */
	private Date time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKF_ALRM.STATUS
	 * @mbg.generated  Fri Jun 15 18:04:35 CST 2018
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKF_ALRM.TOTAL_VALUE
	 * @mbg.generated  Fri Jun 15 18:04:35 CST 2018
	 */
	private Float totalValue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKF_ALRM.DANDER_LAVEL
	 * @mbg.generated  Fri Jun 15 18:04:35 CST 2018
	 */
	private Float dangerLevel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKF_ALRM.SCORE
	 * @mbg.generated  Fri Jun 15 18:04:35 CST 2018
	 */
	private Float score;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKF_ALRM.CLASS
	 * @mbg.generated  Fri Jun 15 18:04:35 CST 2018
	 */
	private String alarmClass;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKF_ALRM.DEFECT_FREQ_ORDER
	 * @mbg.generated  Fri Jun 15 18:04:35 CST 2018
	 */
	private Float defectFreqOrder;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKF_ALRM.BP_TYPE
	 * @mbg.generated  Fri Jun 15 18:04:35 CST 2018
	 */
	private String bpType;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKF_ALRM.ALRM_TIME
	 * @return  the value of SKF_ALRM.ALRM_TIME
	 * @mbg.generated  Fri Jun 15 18:04:35 CST 2018
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKF_ALRM.ALRM_TIME
	 * @param time  the value for SKF_ALRM.ALRM_TIME
	 * @mbg.generated  Fri Jun 15 18:04:35 CST 2018
	 */
	public void setTime(Date time) {
		this.time = time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKF_ALRM.STATUS
	 * @return  the value of SKF_ALRM.STATUS
	 * @mbg.generated  Fri Jun 15 18:04:35 CST 2018
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKF_ALRM.STATUS
	 * @param status  the value for SKF_ALRM.STATUS
	 * @mbg.generated  Fri Jun 15 18:04:35 CST 2018
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKF_ALRM.TOTAL_VALUE
	 * @return  the value of SKF_ALRM.TOTAL_VALUE
	 * @mbg.generated  Fri Jun 15 18:04:35 CST 2018
	 */
	public Float getTotalValue() {
		return totalValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKF_ALRM.TOTAL_VALUE
	 * @param totalValue  the value for SKF_ALRM.TOTAL_VALUE
	 * @mbg.generated  Fri Jun 15 18:04:35 CST 2018
	 */
	public void setTotalValue(Float totalValue) {
		this.totalValue = totalValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKF_ALRM.DANDER_LAVEL
	 * @return  the value of SKF_ALRM.DANDER_LAVEL
	 * @mbg.generated  Fri Jun 15 18:04:35 CST 2018
	 */
	public Float getDangerLevel() {
		return dangerLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKF_ALRM.DANDER_LAVEL
	 * @param dangerLevel  the value for SKF_ALRM.DANDER_LAVEL
	 * @mbg.generated  Fri Jun 15 18:04:35 CST 2018
	 */
	public void setDangerLevel(Float dangerLevel) {
		this.dangerLevel = dangerLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKF_ALRM.SCORE
	 * @return  the value of SKF_ALRM.SCORE
	 * @mbg.generated  Fri Jun 15 18:04:35 CST 2018
	 */
	public Float getScore() {
		return score;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKF_ALRM.SCORE
	 * @param score  the value for SKF_ALRM.SCORE
	 * @mbg.generated  Fri Jun 15 18:04:35 CST 2018
	 */
	public void setScore(Float score) {
		this.score = score;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKF_ALRM.CLASS
	 * @return  the value of SKF_ALRM.CLASS
	 * @mbg.generated  Fri Jun 15 18:04:35 CST 2018
	 */
	public String getAlarmClass() {
		return alarmClass;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKF_ALRM.CLASS
	 * @param alarmClass  the value for SKF_ALRM.CLASS
	 * @mbg.generated  Fri Jun 15 18:04:35 CST 2018
	 */
	public void setAlarmClass(String alarmClass) {
		this.alarmClass = alarmClass;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKF_ALRM.DEFECT_FREQ_ORDER
	 * @return  the value of SKF_ALRM.DEFECT_FREQ_ORDER
	 * @mbg.generated  Fri Jun 15 18:04:35 CST 2018
	 */
	public Float getDefectFreqOrder() {
		return defectFreqOrder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKF_ALRM.DEFECT_FREQ_ORDER
	 * @param defectFreqOrder  the value for SKF_ALRM.DEFECT_FREQ_ORDER
	 * @mbg.generated  Fri Jun 15 18:04:35 CST 2018
	 */
	public void setDefectFreqOrder(Float defectFreqOrder) {
		this.defectFreqOrder = defectFreqOrder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKF_ALRM.BP_TYPE
	 * @return  the value of SKF_ALRM.BP_TYPE
	 * @mbg.generated  Fri Jun 15 18:04:35 CST 2018
	 */
	public String getBpType() {
		return bpType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKF_ALRM.BP_TYPE
	 * @param bpType  the value for SKF_ALRM.BP_TYPE
	 * @mbg.generated  Fri Jun 15 18:04:35 CST 2018
	 */
	public void setBpType(String bpType) {
		this.bpType = bpType;
	}
}