package com.skf.management.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AlarmModelExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table SKF_ALRM
	 * @mbg.generated  Fri Jun 15 17:32:09 CST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table SKF_ALRM
	 * @mbg.generated  Fri Jun 15 17:32:09 CST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table SKF_ALRM
	 * @mbg.generated  Fri Jun 15 17:32:09 CST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SKF_ALRM
	 * @mbg.generated  Fri Jun 15 17:32:09 CST 2018
	 */
	public AlarmModelExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SKF_ALRM
	 * @mbg.generated  Fri Jun 15 17:32:09 CST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SKF_ALRM
	 * @mbg.generated  Fri Jun 15 17:32:09 CST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SKF_ALRM
	 * @mbg.generated  Fri Jun 15 17:32:09 CST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SKF_ALRM
	 * @mbg.generated  Fri Jun 15 17:32:09 CST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SKF_ALRM
	 * @mbg.generated  Fri Jun 15 17:32:09 CST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SKF_ALRM
	 * @mbg.generated  Fri Jun 15 17:32:09 CST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SKF_ALRM
	 * @mbg.generated  Fri Jun 15 17:32:09 CST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SKF_ALRM
	 * @mbg.generated  Fri Jun 15 17:32:09 CST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SKF_ALRM
	 * @mbg.generated  Fri Jun 15 17:32:09 CST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SKF_ALRM
	 * @mbg.generated  Fri Jun 15 17:32:09 CST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table SKF_ALRM
	 * @mbg.generated  Fri Jun 15 17:32:09 CST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andCodeIsNull() {
			addCriterion("CMPT_CODE is null");
			return (Criteria) this;
		}

		public Criteria andCodeIsNotNull() {
			addCriterion("CMPT_CODE is not null");
			return (Criteria) this;
		}

		public Criteria andCodeEqualTo(String value) {
			addCriterion("CMPT_CODE =", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotEqualTo(String value) {
			addCriterion("CMPT_CODE <>", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeGreaterThan(String value) {
			addCriterion("CMPT_CODE >", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeGreaterThanOrEqualTo(String value) {
			addCriterion("CMPT_CODE >=", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLessThan(String value) {
			addCriterion("CMPT_CODE <", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLessThanOrEqualTo(String value) {
			addCriterion("CMPT_CODE <=", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLike(String value) {
			addCriterion("CMPT_CODE like", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotLike(String value) {
			addCriterion("CMPT_CODE not like", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeIn(List<String> values) {
			addCriterion("CMPT_CODE in", values, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotIn(List<String> values) {
			addCriterion("CMPT_CODE not in", values, "code");
			return (Criteria) this;
		}

		public Criteria andCodeBetween(String value1, String value2) {
			addCriterion("CMPT_CODE between", value1, value2, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotBetween(String value1, String value2) {
			addCriterion("CMPT_CODE not between", value1, value2, "code");
			return (Criteria) this;
		}

		public Criteria andTypeIsNull() {
			addCriterion("ALRM_TYPE is null");
			return (Criteria) this;
		}

		public Criteria andTypeIsNotNull() {
			addCriterion("ALRM_TYPE is not null");
			return (Criteria) this;
		}

		public Criteria andTypeEqualTo(Integer value) {
			addCriterion("ALRM_TYPE =", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotEqualTo(Integer value) {
			addCriterion("ALRM_TYPE <>", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThan(Integer value) {
			addCriterion("ALRM_TYPE >", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("ALRM_TYPE >=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThan(Integer value) {
			addCriterion("ALRM_TYPE <", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThanOrEqualTo(Integer value) {
			addCriterion("ALRM_TYPE <=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeIn(List<Integer> values) {
			addCriterion("ALRM_TYPE in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotIn(List<Integer> values) {
			addCriterion("ALRM_TYPE not in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeBetween(Integer value1, Integer value2) {
			addCriterion("ALRM_TYPE between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("ALRM_TYPE not between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andTimeIsNull() {
			addCriterion("ALRM_TIME is null");
			return (Criteria) this;
		}

		public Criteria andTimeIsNotNull() {
			addCriterion("ALRM_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andTimeEqualTo(Date value) {
			addCriterion("ALRM_TIME =", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeNotEqualTo(Date value) {
			addCriterion("ALRM_TIME <>", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeGreaterThan(Date value) {
			addCriterion("ALRM_TIME >", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("ALRM_TIME >=", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeLessThan(Date value) {
			addCriterion("ALRM_TIME <", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeLessThanOrEqualTo(Date value) {
			addCriterion("ALRM_TIME <=", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeIn(List<Date> values) {
			addCriterion("ALRM_TIME in", values, "time");
			return (Criteria) this;
		}

		public Criteria andTimeNotIn(List<Date> values) {
			addCriterion("ALRM_TIME not in", values, "time");
			return (Criteria) this;
		}

		public Criteria andTimeBetween(Date value1, Date value2) {
			addCriterion("ALRM_TIME between", value1, value2, "time");
			return (Criteria) this;
		}

		public Criteria andTimeNotBetween(Date value1, Date value2) {
			addCriterion("ALRM_TIME not between", value1, value2, "time");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("STATUS is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("STATUS is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(Integer value) {
			addCriterion("STATUS =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(Integer value) {
			addCriterion("STATUS <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(Integer value) {
			addCriterion("STATUS >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("STATUS >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(Integer value) {
			addCriterion("STATUS <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(Integer value) {
			addCriterion("STATUS <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<Integer> values) {
			addCriterion("STATUS in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<Integer> values) {
			addCriterion("STATUS not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(Integer value1, Integer value2) {
			addCriterion("STATUS between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("STATUS not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andTotalValueIsNull() {
			addCriterion("TOTAL_VALUE is null");
			return (Criteria) this;
		}

		public Criteria andTotalValueIsNotNull() {
			addCriterion("TOTAL_VALUE is not null");
			return (Criteria) this;
		}

		public Criteria andTotalValueEqualTo(Float value) {
			addCriterion("TOTAL_VALUE =", value, "totalValue");
			return (Criteria) this;
		}

		public Criteria andTotalValueNotEqualTo(Float value) {
			addCriterion("TOTAL_VALUE <>", value, "totalValue");
			return (Criteria) this;
		}

		public Criteria andTotalValueGreaterThan(Float value) {
			addCriterion("TOTAL_VALUE >", value, "totalValue");
			return (Criteria) this;
		}

		public Criteria andTotalValueGreaterThanOrEqualTo(Float value) {
			addCriterion("TOTAL_VALUE >=", value, "totalValue");
			return (Criteria) this;
		}

		public Criteria andTotalValueLessThan(Float value) {
			addCriterion("TOTAL_VALUE <", value, "totalValue");
			return (Criteria) this;
		}

		public Criteria andTotalValueLessThanOrEqualTo(Float value) {
			addCriterion("TOTAL_VALUE <=", value, "totalValue");
			return (Criteria) this;
		}

		public Criteria andTotalValueIn(List<Float> values) {
			addCriterion("TOTAL_VALUE in", values, "totalValue");
			return (Criteria) this;
		}

		public Criteria andTotalValueNotIn(List<Float> values) {
			addCriterion("TOTAL_VALUE not in", values, "totalValue");
			return (Criteria) this;
		}

		public Criteria andTotalValueBetween(Float value1, Float value2) {
			addCriterion("TOTAL_VALUE between", value1, value2, "totalValue");
			return (Criteria) this;
		}

		public Criteria andTotalValueNotBetween(Float value1, Float value2) {
			addCriterion("TOTAL_VALUE not between", value1, value2, "totalValue");
			return (Criteria) this;
		}

		public Criteria andDangerLevelIsNull() {
			addCriterion("DANDER_LAVEL is null");
			return (Criteria) this;
		}

		public Criteria andDangerLevelIsNotNull() {
			addCriterion("DANDER_LAVEL is not null");
			return (Criteria) this;
		}

		public Criteria andDangerLevelEqualTo(Float value) {
			addCriterion("DANDER_LAVEL =", value, "dangerLevel");
			return (Criteria) this;
		}

		public Criteria andDangerLevelNotEqualTo(Float value) {
			addCriterion("DANDER_LAVEL <>", value, "dangerLevel");
			return (Criteria) this;
		}

		public Criteria andDangerLevelGreaterThan(Float value) {
			addCriterion("DANDER_LAVEL >", value, "dangerLevel");
			return (Criteria) this;
		}

		public Criteria andDangerLevelGreaterThanOrEqualTo(Float value) {
			addCriterion("DANDER_LAVEL >=", value, "dangerLevel");
			return (Criteria) this;
		}

		public Criteria andDangerLevelLessThan(Float value) {
			addCriterion("DANDER_LAVEL <", value, "dangerLevel");
			return (Criteria) this;
		}

		public Criteria andDangerLevelLessThanOrEqualTo(Float value) {
			addCriterion("DANDER_LAVEL <=", value, "dangerLevel");
			return (Criteria) this;
		}

		public Criteria andDangerLevelIn(List<Float> values) {
			addCriterion("DANDER_LAVEL in", values, "dangerLevel");
			return (Criteria) this;
		}

		public Criteria andDangerLevelNotIn(List<Float> values) {
			addCriterion("DANDER_LAVEL not in", values, "dangerLevel");
			return (Criteria) this;
		}

		public Criteria andDangerLevelBetween(Float value1, Float value2) {
			addCriterion("DANDER_LAVEL between", value1, value2, "dangerLevel");
			return (Criteria) this;
		}

		public Criteria andDangerLevelNotBetween(Float value1, Float value2) {
			addCriterion("DANDER_LAVEL not between", value1, value2, "dangerLevel");
			return (Criteria) this;
		}

		public Criteria andScoreIsNull() {
			addCriterion("SCORE is null");
			return (Criteria) this;
		}

		public Criteria andScoreIsNotNull() {
			addCriterion("SCORE is not null");
			return (Criteria) this;
		}

		public Criteria andScoreEqualTo(Float value) {
			addCriterion("SCORE =", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreNotEqualTo(Float value) {
			addCriterion("SCORE <>", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreGreaterThan(Float value) {
			addCriterion("SCORE >", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreGreaterThanOrEqualTo(Float value) {
			addCriterion("SCORE >=", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreLessThan(Float value) {
			addCriterion("SCORE <", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreLessThanOrEqualTo(Float value) {
			addCriterion("SCORE <=", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreIn(List<Float> values) {
			addCriterion("SCORE in", values, "score");
			return (Criteria) this;
		}

		public Criteria andScoreNotIn(List<Float> values) {
			addCriterion("SCORE not in", values, "score");
			return (Criteria) this;
		}

		public Criteria andScoreBetween(Float value1, Float value2) {
			addCriterion("SCORE between", value1, value2, "score");
			return (Criteria) this;
		}

		public Criteria andScoreNotBetween(Float value1, Float value2) {
			addCriterion("SCORE not between", value1, value2, "score");
			return (Criteria) this;
		}

		public Criteria andAlarmClassIsNull() {
			addCriterion("CLASS is null");
			return (Criteria) this;
		}

		public Criteria andAlarmClassIsNotNull() {
			addCriterion("CLASS is not null");
			return (Criteria) this;
		}

		public Criteria andAlarmClassEqualTo(String value) {
			addCriterion("CLASS =", value, "alarmClass");
			return (Criteria) this;
		}

		public Criteria andAlarmClassNotEqualTo(String value) {
			addCriterion("CLASS <>", value, "alarmClass");
			return (Criteria) this;
		}

		public Criteria andAlarmClassGreaterThan(String value) {
			addCriterion("CLASS >", value, "alarmClass");
			return (Criteria) this;
		}

		public Criteria andAlarmClassGreaterThanOrEqualTo(String value) {
			addCriterion("CLASS >=", value, "alarmClass");
			return (Criteria) this;
		}

		public Criteria andAlarmClassLessThan(String value) {
			addCriterion("CLASS <", value, "alarmClass");
			return (Criteria) this;
		}

		public Criteria andAlarmClassLessThanOrEqualTo(String value) {
			addCriterion("CLASS <=", value, "alarmClass");
			return (Criteria) this;
		}

		public Criteria andAlarmClassLike(String value) {
			addCriterion("CLASS like", value, "alarmClass");
			return (Criteria) this;
		}

		public Criteria andAlarmClassNotLike(String value) {
			addCriterion("CLASS not like", value, "alarmClass");
			return (Criteria) this;
		}

		public Criteria andAlarmClassIn(List<String> values) {
			addCriterion("CLASS in", values, "alarmClass");
			return (Criteria) this;
		}

		public Criteria andAlarmClassNotIn(List<String> values) {
			addCriterion("CLASS not in", values, "alarmClass");
			return (Criteria) this;
		}

		public Criteria andAlarmClassBetween(String value1, String value2) {
			addCriterion("CLASS between", value1, value2, "alarmClass");
			return (Criteria) this;
		}

		public Criteria andAlarmClassNotBetween(String value1, String value2) {
			addCriterion("CLASS not between", value1, value2, "alarmClass");
			return (Criteria) this;
		}

		public Criteria andDefectFreqOrderIsNull() {
			addCriterion("DEFECT_FREQ_ORDER is null");
			return (Criteria) this;
		}

		public Criteria andDefectFreqOrderIsNotNull() {
			addCriterion("DEFECT_FREQ_ORDER is not null");
			return (Criteria) this;
		}

		public Criteria andDefectFreqOrderEqualTo(Float value) {
			addCriterion("DEFECT_FREQ_ORDER =", value, "defectFreqOrder");
			return (Criteria) this;
		}

		public Criteria andDefectFreqOrderNotEqualTo(Float value) {
			addCriterion("DEFECT_FREQ_ORDER <>", value, "defectFreqOrder");
			return (Criteria) this;
		}

		public Criteria andDefectFreqOrderGreaterThan(Float value) {
			addCriterion("DEFECT_FREQ_ORDER >", value, "defectFreqOrder");
			return (Criteria) this;
		}

		public Criteria andDefectFreqOrderGreaterThanOrEqualTo(Float value) {
			addCriterion("DEFECT_FREQ_ORDER >=", value, "defectFreqOrder");
			return (Criteria) this;
		}

		public Criteria andDefectFreqOrderLessThan(Float value) {
			addCriterion("DEFECT_FREQ_ORDER <", value, "defectFreqOrder");
			return (Criteria) this;
		}

		public Criteria andDefectFreqOrderLessThanOrEqualTo(Float value) {
			addCriterion("DEFECT_FREQ_ORDER <=", value, "defectFreqOrder");
			return (Criteria) this;
		}

		public Criteria andDefectFreqOrderIn(List<Float> values) {
			addCriterion("DEFECT_FREQ_ORDER in", values, "defectFreqOrder");
			return (Criteria) this;
		}

		public Criteria andDefectFreqOrderNotIn(List<Float> values) {
			addCriterion("DEFECT_FREQ_ORDER not in", values, "defectFreqOrder");
			return (Criteria) this;
		}

		public Criteria andDefectFreqOrderBetween(Float value1, Float value2) {
			addCriterion("DEFECT_FREQ_ORDER between", value1, value2, "defectFreqOrder");
			return (Criteria) this;
		}

		public Criteria andDefectFreqOrderNotBetween(Float value1, Float value2) {
			addCriterion("DEFECT_FREQ_ORDER not between", value1, value2, "defectFreqOrder");
			return (Criteria) this;
		}

		public Criteria andBpTypeIsNull() {
			addCriterion("BP_TYPE is null");
			return (Criteria) this;
		}

		public Criteria andBpTypeIsNotNull() {
			addCriterion("BP_TYPE is not null");
			return (Criteria) this;
		}

		public Criteria andBpTypeEqualTo(String value) {
			addCriterion("BP_TYPE =", value, "bpType");
			return (Criteria) this;
		}

		public Criteria andBpTypeNotEqualTo(String value) {
			addCriterion("BP_TYPE <>", value, "bpType");
			return (Criteria) this;
		}

		public Criteria andBpTypeGreaterThan(String value) {
			addCriterion("BP_TYPE >", value, "bpType");
			return (Criteria) this;
		}

		public Criteria andBpTypeGreaterThanOrEqualTo(String value) {
			addCriterion("BP_TYPE >=", value, "bpType");
			return (Criteria) this;
		}

		public Criteria andBpTypeLessThan(String value) {
			addCriterion("BP_TYPE <", value, "bpType");
			return (Criteria) this;
		}

		public Criteria andBpTypeLessThanOrEqualTo(String value) {
			addCriterion("BP_TYPE <=", value, "bpType");
			return (Criteria) this;
		}

		public Criteria andBpTypeLike(String value) {
			addCriterion("BP_TYPE like", value, "bpType");
			return (Criteria) this;
		}

		public Criteria andBpTypeNotLike(String value) {
			addCriterion("BP_TYPE not like", value, "bpType");
			return (Criteria) this;
		}

		public Criteria andBpTypeIn(List<String> values) {
			addCriterion("BP_TYPE in", values, "bpType");
			return (Criteria) this;
		}

		public Criteria andBpTypeNotIn(List<String> values) {
			addCriterion("BP_TYPE not in", values, "bpType");
			return (Criteria) this;
		}

		public Criteria andBpTypeBetween(String value1, String value2) {
			addCriterion("BP_TYPE between", value1, value2, "bpType");
			return (Criteria) this;
		}

		public Criteria andBpTypeNotBetween(String value1, String value2) {
			addCriterion("BP_TYPE not between", value1, value2, "bpType");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table SKF_ALRM
	 * @mbg.generated  Fri Jun 15 17:32:09 CST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SKF_ALRM
     *
     * @mbg.generated do_not_delete_during_merge Fri Jun 08 14:32:24 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}