package com.skf.management.model;

import java.util.ArrayList;
import java.util.List;

public class BearingModelExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table SKF_BRNG
	 * @mbg.generated  Fri Jun 15 17:32:09 CST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table SKF_BRNG
	 * @mbg.generated  Fri Jun 15 17:32:09 CST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table SKF_BRNG
	 * @mbg.generated  Fri Jun 15 17:32:09 CST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SKF_BRNG
	 * @mbg.generated  Fri Jun 15 17:32:09 CST 2018
	 */
	public BearingModelExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SKF_BRNG
	 * @mbg.generated  Fri Jun 15 17:32:09 CST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SKF_BRNG
	 * @mbg.generated  Fri Jun 15 17:32:09 CST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SKF_BRNG
	 * @mbg.generated  Fri Jun 15 17:32:09 CST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SKF_BRNG
	 * @mbg.generated  Fri Jun 15 17:32:09 CST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SKF_BRNG
	 * @mbg.generated  Fri Jun 15 17:32:09 CST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SKF_BRNG
	 * @mbg.generated  Fri Jun 15 17:32:09 CST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SKF_BRNG
	 * @mbg.generated  Fri Jun 15 17:32:09 CST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SKF_BRNG
	 * @mbg.generated  Fri Jun 15 17:32:09 CST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SKF_BRNG
	 * @mbg.generated  Fri Jun 15 17:32:09 CST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SKF_BRNG
	 * @mbg.generated  Fri Jun 15 17:32:09 CST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table SKF_BRNG
	 * @mbg.generated  Fri Jun 15 17:32:09 CST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andCodeIsNull() {
			addCriterion("BRNG_CODE is null");
			return (Criteria) this;
		}

		public Criteria andCodeIsNotNull() {
			addCriterion("BRNG_CODE is not null");
			return (Criteria) this;
		}

		public Criteria andCodeEqualTo(String value) {
			addCriterion("BRNG_CODE =", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotEqualTo(String value) {
			addCriterion("BRNG_CODE <>", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeGreaterThan(String value) {
			addCriterion("BRNG_CODE >", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeGreaterThanOrEqualTo(String value) {
			addCriterion("BRNG_CODE >=", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLessThan(String value) {
			addCriterion("BRNG_CODE <", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLessThanOrEqualTo(String value) {
			addCriterion("BRNG_CODE <=", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLike(String value) {
			addCriterion("BRNG_CODE like", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotLike(String value) {
			addCriterion("BRNG_CODE not like", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeIn(List<String> values) {
			addCriterion("BRNG_CODE in", values, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotIn(List<String> values) {
			addCriterion("BRNG_CODE not in", values, "code");
			return (Criteria) this;
		}

		public Criteria andCodeBetween(String value1, String value2) {
			addCriterion("BRNG_CODE between", value1, value2, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotBetween(String value1, String value2) {
			addCriterion("BRNG_CODE not between", value1, value2, "code");
			return (Criteria) this;
		}

		public Criteria andModelNumberIsNull() {
			addCriterion("BRNG_MODEL_NUMBER is null");
			return (Criteria) this;
		}

		public Criteria andModelNumberIsNotNull() {
			addCriterion("BRNG_MODEL_NUMBER is not null");
			return (Criteria) this;
		}

		public Criteria andModelNumberEqualTo(String value) {
			addCriterion("BRNG_MODEL_NUMBER =", value, "modelNumber");
			return (Criteria) this;
		}

		public Criteria andModelNumberNotEqualTo(String value) {
			addCriterion("BRNG_MODEL_NUMBER <>", value, "modelNumber");
			return (Criteria) this;
		}

		public Criteria andModelNumberGreaterThan(String value) {
			addCriterion("BRNG_MODEL_NUMBER >", value, "modelNumber");
			return (Criteria) this;
		}

		public Criteria andModelNumberGreaterThanOrEqualTo(String value) {
			addCriterion("BRNG_MODEL_NUMBER >=", value, "modelNumber");
			return (Criteria) this;
		}

		public Criteria andModelNumberLessThan(String value) {
			addCriterion("BRNG_MODEL_NUMBER <", value, "modelNumber");
			return (Criteria) this;
		}

		public Criteria andModelNumberLessThanOrEqualTo(String value) {
			addCriterion("BRNG_MODEL_NUMBER <=", value, "modelNumber");
			return (Criteria) this;
		}

		public Criteria andModelNumberLike(String value) {
			addCriterion("BRNG_MODEL_NUMBER like", value, "modelNumber");
			return (Criteria) this;
		}

		public Criteria andModelNumberNotLike(String value) {
			addCriterion("BRNG_MODEL_NUMBER not like", value, "modelNumber");
			return (Criteria) this;
		}

		public Criteria andModelNumberIn(List<String> values) {
			addCriterion("BRNG_MODEL_NUMBER in", values, "modelNumber");
			return (Criteria) this;
		}

		public Criteria andModelNumberNotIn(List<String> values) {
			addCriterion("BRNG_MODEL_NUMBER not in", values, "modelNumber");
			return (Criteria) this;
		}

		public Criteria andModelNumberBetween(String value1, String value2) {
			addCriterion("BRNG_MODEL_NUMBER between", value1, value2, "modelNumber");
			return (Criteria) this;
		}

		public Criteria andModelNumberNotBetween(String value1, String value2) {
			addCriterion("BRNG_MODEL_NUMBER not between", value1, value2, "modelNumber");
			return (Criteria) this;
		}

		public Criteria andManufactureIsNull() {
			addCriterion("BRNG_MANUFACTURE is null");
			return (Criteria) this;
		}

		public Criteria andManufactureIsNotNull() {
			addCriterion("BRNG_MANUFACTURE is not null");
			return (Criteria) this;
		}

		public Criteria andManufactureEqualTo(String value) {
			addCriterion("BRNG_MANUFACTURE =", value, "manufacture");
			return (Criteria) this;
		}

		public Criteria andManufactureNotEqualTo(String value) {
			addCriterion("BRNG_MANUFACTURE <>", value, "manufacture");
			return (Criteria) this;
		}

		public Criteria andManufactureGreaterThan(String value) {
			addCriterion("BRNG_MANUFACTURE >", value, "manufacture");
			return (Criteria) this;
		}

		public Criteria andManufactureGreaterThanOrEqualTo(String value) {
			addCriterion("BRNG_MANUFACTURE >=", value, "manufacture");
			return (Criteria) this;
		}

		public Criteria andManufactureLessThan(String value) {
			addCriterion("BRNG_MANUFACTURE <", value, "manufacture");
			return (Criteria) this;
		}

		public Criteria andManufactureLessThanOrEqualTo(String value) {
			addCriterion("BRNG_MANUFACTURE <=", value, "manufacture");
			return (Criteria) this;
		}

		public Criteria andManufactureLike(String value) {
			addCriterion("BRNG_MANUFACTURE like", value, "manufacture");
			return (Criteria) this;
		}

		public Criteria andManufactureNotLike(String value) {
			addCriterion("BRNG_MANUFACTURE not like", value, "manufacture");
			return (Criteria) this;
		}

		public Criteria andManufactureIn(List<String> values) {
			addCriterion("BRNG_MANUFACTURE in", values, "manufacture");
			return (Criteria) this;
		}

		public Criteria andManufactureNotIn(List<String> values) {
			addCriterion("BRNG_MANUFACTURE not in", values, "manufacture");
			return (Criteria) this;
		}

		public Criteria andManufactureBetween(String value1, String value2) {
			addCriterion("BRNG_MANUFACTURE between", value1, value2, "manufacture");
			return (Criteria) this;
		}

		public Criteria andManufactureNotBetween(String value1, String value2) {
			addCriterion("BRNG_MANUFACTURE not between", value1, value2, "manufacture");
			return (Criteria) this;
		}

		public Criteria andDescriptionIsNull() {
			addCriterion("BRNG_DESCRIPTION is null");
			return (Criteria) this;
		}

		public Criteria andDescriptionIsNotNull() {
			addCriterion("BRNG_DESCRIPTION is not null");
			return (Criteria) this;
		}

		public Criteria andDescriptionEqualTo(String value) {
			addCriterion("BRNG_DESCRIPTION =", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotEqualTo(String value) {
			addCriterion("BRNG_DESCRIPTION <>", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionGreaterThan(String value) {
			addCriterion("BRNG_DESCRIPTION >", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
			addCriterion("BRNG_DESCRIPTION >=", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLessThan(String value) {
			addCriterion("BRNG_DESCRIPTION <", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLessThanOrEqualTo(String value) {
			addCriterion("BRNG_DESCRIPTION <=", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLike(String value) {
			addCriterion("BRNG_DESCRIPTION like", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotLike(String value) {
			addCriterion("BRNG_DESCRIPTION not like", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionIn(List<String> values) {
			addCriterion("BRNG_DESCRIPTION in", values, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotIn(List<String> values) {
			addCriterion("BRNG_DESCRIPTION not in", values, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionBetween(String value1, String value2) {
			addCriterion("BRNG_DESCRIPTION between", value1, value2, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotBetween(String value1, String value2) {
			addCriterion("BRNG_DESCRIPTION not between", value1, value2, "description");
			return (Criteria) this;
		}

		public Criteria andBpfoIsNull() {
			addCriterion("BRNG_BPFO is null");
			return (Criteria) this;
		}

		public Criteria andBpfoIsNotNull() {
			addCriterion("BRNG_BPFO is not null");
			return (Criteria) this;
		}

		public Criteria andBpfoEqualTo(Float value) {
			addCriterion("BRNG_BPFO =", value, "bpfo");
			return (Criteria) this;
		}

		public Criteria andBpfoNotEqualTo(Float value) {
			addCriterion("BRNG_BPFO <>", value, "bpfo");
			return (Criteria) this;
		}

		public Criteria andBpfoGreaterThan(Float value) {
			addCriterion("BRNG_BPFO >", value, "bpfo");
			return (Criteria) this;
		}

		public Criteria andBpfoGreaterThanOrEqualTo(Float value) {
			addCriterion("BRNG_BPFO >=", value, "bpfo");
			return (Criteria) this;
		}

		public Criteria andBpfoLessThan(Float value) {
			addCriterion("BRNG_BPFO <", value, "bpfo");
			return (Criteria) this;
		}

		public Criteria andBpfoLessThanOrEqualTo(Float value) {
			addCriterion("BRNG_BPFO <=", value, "bpfo");
			return (Criteria) this;
		}

		public Criteria andBpfoIn(List<Float> values) {
			addCriterion("BRNG_BPFO in", values, "bpfo");
			return (Criteria) this;
		}

		public Criteria andBpfoNotIn(List<Float> values) {
			addCriterion("BRNG_BPFO not in", values, "bpfo");
			return (Criteria) this;
		}

		public Criteria andBpfoBetween(Float value1, Float value2) {
			addCriterion("BRNG_BPFO between", value1, value2, "bpfo");
			return (Criteria) this;
		}

		public Criteria andBpfoNotBetween(Float value1, Float value2) {
			addCriterion("BRNG_BPFO not between", value1, value2, "bpfo");
			return (Criteria) this;
		}

		public Criteria andBpfiIsNull() {
			addCriterion("BRNG_BPFI is null");
			return (Criteria) this;
		}

		public Criteria andBpfiIsNotNull() {
			addCriterion("BRNG_BPFI is not null");
			return (Criteria) this;
		}

		public Criteria andBpfiEqualTo(Float value) {
			addCriterion("BRNG_BPFI =", value, "bpfi");
			return (Criteria) this;
		}

		public Criteria andBpfiNotEqualTo(Float value) {
			addCriterion("BRNG_BPFI <>", value, "bpfi");
			return (Criteria) this;
		}

		public Criteria andBpfiGreaterThan(Float value) {
			addCriterion("BRNG_BPFI >", value, "bpfi");
			return (Criteria) this;
		}

		public Criteria andBpfiGreaterThanOrEqualTo(Float value) {
			addCriterion("BRNG_BPFI >=", value, "bpfi");
			return (Criteria) this;
		}

		public Criteria andBpfiLessThan(Float value) {
			addCriterion("BRNG_BPFI <", value, "bpfi");
			return (Criteria) this;
		}

		public Criteria andBpfiLessThanOrEqualTo(Float value) {
			addCriterion("BRNG_BPFI <=", value, "bpfi");
			return (Criteria) this;
		}

		public Criteria andBpfiIn(List<Float> values) {
			addCriterion("BRNG_BPFI in", values, "bpfi");
			return (Criteria) this;
		}

		public Criteria andBpfiNotIn(List<Float> values) {
			addCriterion("BRNG_BPFI not in", values, "bpfi");
			return (Criteria) this;
		}

		public Criteria andBpfiBetween(Float value1, Float value2) {
			addCriterion("BRNG_BPFI between", value1, value2, "bpfi");
			return (Criteria) this;
		}

		public Criteria andBpfiNotBetween(Float value1, Float value2) {
			addCriterion("BRNG_BPFI not between", value1, value2, "bpfi");
			return (Criteria) this;
		}

		public Criteria andBsfIsNull() {
			addCriterion("BRNG_BSF is null");
			return (Criteria) this;
		}

		public Criteria andBsfIsNotNull() {
			addCriterion("BRNG_BSF is not null");
			return (Criteria) this;
		}

		public Criteria andBsfEqualTo(Float value) {
			addCriterion("BRNG_BSF =", value, "bsf");
			return (Criteria) this;
		}

		public Criteria andBsfNotEqualTo(Float value) {
			addCriterion("BRNG_BSF <>", value, "bsf");
			return (Criteria) this;
		}

		public Criteria andBsfGreaterThan(Float value) {
			addCriterion("BRNG_BSF >", value, "bsf");
			return (Criteria) this;
		}

		public Criteria andBsfGreaterThanOrEqualTo(Float value) {
			addCriterion("BRNG_BSF >=", value, "bsf");
			return (Criteria) this;
		}

		public Criteria andBsfLessThan(Float value) {
			addCriterion("BRNG_BSF <", value, "bsf");
			return (Criteria) this;
		}

		public Criteria andBsfLessThanOrEqualTo(Float value) {
			addCriterion("BRNG_BSF <=", value, "bsf");
			return (Criteria) this;
		}

		public Criteria andBsfIn(List<Float> values) {
			addCriterion("BRNG_BSF in", values, "bsf");
			return (Criteria) this;
		}

		public Criteria andBsfNotIn(List<Float> values) {
			addCriterion("BRNG_BSF not in", values, "bsf");
			return (Criteria) this;
		}

		public Criteria andBsfBetween(Float value1, Float value2) {
			addCriterion("BRNG_BSF between", value1, value2, "bsf");
			return (Criteria) this;
		}

		public Criteria andBsfNotBetween(Float value1, Float value2) {
			addCriterion("BRNG_BSF not between", value1, value2, "bsf");
			return (Criteria) this;
		}

		public Criteria andFtfIsNull() {
			addCriterion("BRNG_FTF is null");
			return (Criteria) this;
		}

		public Criteria andFtfIsNotNull() {
			addCriterion("BRNG_FTF is not null");
			return (Criteria) this;
		}

		public Criteria andFtfEqualTo(Float value) {
			addCriterion("BRNG_FTF =", value, "ftf");
			return (Criteria) this;
		}

		public Criteria andFtfNotEqualTo(Float value) {
			addCriterion("BRNG_FTF <>", value, "ftf");
			return (Criteria) this;
		}

		public Criteria andFtfGreaterThan(Float value) {
			addCriterion("BRNG_FTF >", value, "ftf");
			return (Criteria) this;
		}

		public Criteria andFtfGreaterThanOrEqualTo(Float value) {
			addCriterion("BRNG_FTF >=", value, "ftf");
			return (Criteria) this;
		}

		public Criteria andFtfLessThan(Float value) {
			addCriterion("BRNG_FTF <", value, "ftf");
			return (Criteria) this;
		}

		public Criteria andFtfLessThanOrEqualTo(Float value) {
			addCriterion("BRNG_FTF <=", value, "ftf");
			return (Criteria) this;
		}

		public Criteria andFtfIn(List<Float> values) {
			addCriterion("BRNG_FTF in", values, "ftf");
			return (Criteria) this;
		}

		public Criteria andFtfNotIn(List<Float> values) {
			addCriterion("BRNG_FTF not in", values, "ftf");
			return (Criteria) this;
		}

		public Criteria andFtfBetween(Float value1, Float value2) {
			addCriterion("BRNG_FTF between", value1, value2, "ftf");
			return (Criteria) this;
		}

		public Criteria andFtfNotBetween(Float value1, Float value2) {
			addCriterion("BRNG_FTF not between", value1, value2, "ftf");
			return (Criteria) this;
		}

		public Criteria andImageCodeIsNull() {
			addCriterion("BRNG_IMAGE_CODE is null");
			return (Criteria) this;
		}

		public Criteria andImageCodeIsNotNull() {
			addCriterion("BRNG_IMAGE_CODE is not null");
			return (Criteria) this;
		}

		public Criteria andImageCodeEqualTo(String value) {
			addCriterion("BRNG_IMAGE_CODE =", value, "imageCode");
			return (Criteria) this;
		}

		public Criteria andImageCodeNotEqualTo(String value) {
			addCriterion("BRNG_IMAGE_CODE <>", value, "imageCode");
			return (Criteria) this;
		}

		public Criteria andImageCodeGreaterThan(String value) {
			addCriterion("BRNG_IMAGE_CODE >", value, "imageCode");
			return (Criteria) this;
		}

		public Criteria andImageCodeGreaterThanOrEqualTo(String value) {
			addCriterion("BRNG_IMAGE_CODE >=", value, "imageCode");
			return (Criteria) this;
		}

		public Criteria andImageCodeLessThan(String value) {
			addCriterion("BRNG_IMAGE_CODE <", value, "imageCode");
			return (Criteria) this;
		}

		public Criteria andImageCodeLessThanOrEqualTo(String value) {
			addCriterion("BRNG_IMAGE_CODE <=", value, "imageCode");
			return (Criteria) this;
		}

		public Criteria andImageCodeLike(String value) {
			addCriterion("BRNG_IMAGE_CODE like", value, "imageCode");
			return (Criteria) this;
		}

		public Criteria andImageCodeNotLike(String value) {
			addCriterion("BRNG_IMAGE_CODE not like", value, "imageCode");
			return (Criteria) this;
		}

		public Criteria andImageCodeIn(List<String> values) {
			addCriterion("BRNG_IMAGE_CODE in", values, "imageCode");
			return (Criteria) this;
		}

		public Criteria andImageCodeNotIn(List<String> values) {
			addCriterion("BRNG_IMAGE_CODE not in", values, "imageCode");
			return (Criteria) this;
		}

		public Criteria andImageCodeBetween(String value1, String value2) {
			addCriterion("BRNG_IMAGE_CODE between", value1, value2, "imageCode");
			return (Criteria) this;
		}

		public Criteria andImageCodeNotBetween(String value1, String value2) {
			addCriterion("BRNG_IMAGE_CODE not between", value1, value2, "imageCode");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table SKF_BRNG
	 * @mbg.generated  Fri Jun 15 17:32:09 CST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table skf_brng
     *
     * @mbg.generated do_not_delete_during_merge Thu May 31 17:23:14 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}