package com.skf.management.model;

public class BearingModel {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf_brng.BRNG_CODE
	 * @mbg.generated  Tue Jun 05 15:12:19 CST 2018
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf_brng.BRNG_MODEL_NUMBER
	 * @mbg.generated  Tue Jun 05 15:12:19 CST 2018
	 */
	private Integer modelNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf_brng.BRNG_MANUFACTURE
	 * @mbg.generated  Tue Jun 05 15:12:19 CST 2018
	 */
	private String manufacture;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf_brng.BRNG_DESCRIPTION
	 * @mbg.generated  Tue Jun 05 15:12:19 CST 2018
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf_brng.BRNG_BPFO
	 * @mbg.generated  Tue Jun 05 15:12:19 CST 2018
	 */
	private Float bpfo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf_brng.BRNG_BPFI
	 * @mbg.generated  Tue Jun 05 15:12:19 CST 2018
	 */
	private Float bpfi;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf_brng.BRNG_BSF
	 * @mbg.generated  Tue Jun 05 15:12:19 CST 2018
	 */
	private Float bsf;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf_brng.BRNG_FTF
	 * @mbg.generated  Tue Jun 05 15:12:19 CST 2018
	 */
	private Float ftf;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf_brng.BRNG_IMAGE_CODE
	 * @mbg.generated  Tue Jun 05 15:12:19 CST 2018
	 */
	private String imageCode;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf_brng.BRNG_CODE
	 * @return  the value of skf_brng.BRNG_CODE
	 * @mbg.generated  Tue Jun 05 15:12:19 CST 2018
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf_brng.BRNG_CODE
	 * @param code  the value for skf_brng.BRNG_CODE
	 * @mbg.generated  Tue Jun 05 15:12:19 CST 2018
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf_brng.BRNG_MODEL_NUMBER
	 * @return  the value of skf_brng.BRNG_MODEL_NUMBER
	 * @mbg.generated  Tue Jun 05 15:12:19 CST 2018
	 */
	public Integer getModelNumber() {
		return modelNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf_brng.BRNG_MODEL_NUMBER
	 * @param modelNumber  the value for skf_brng.BRNG_MODEL_NUMBER
	 * @mbg.generated  Tue Jun 05 15:12:19 CST 2018
	 */
	public void setModelNumber(Integer modelNumber) {
		this.modelNumber = modelNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf_brng.BRNG_MANUFACTURE
	 * @return  the value of skf_brng.BRNG_MANUFACTURE
	 * @mbg.generated  Tue Jun 05 15:12:19 CST 2018
	 */
	public String getManufacture() {
		return manufacture;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf_brng.BRNG_MANUFACTURE
	 * @param manufacture  the value for skf_brng.BRNG_MANUFACTURE
	 * @mbg.generated  Tue Jun 05 15:12:19 CST 2018
	 */
	public void setManufacture(String manufacture) {
		this.manufacture = manufacture;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf_brng.BRNG_DESCRIPTION
	 * @return  the value of skf_brng.BRNG_DESCRIPTION
	 * @mbg.generated  Tue Jun 05 15:12:19 CST 2018
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf_brng.BRNG_DESCRIPTION
	 * @param description  the value for skf_brng.BRNG_DESCRIPTION
	 * @mbg.generated  Tue Jun 05 15:12:19 CST 2018
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf_brng.BRNG_BPFO
	 * @return  the value of skf_brng.BRNG_BPFO
	 * @mbg.generated  Tue Jun 05 15:12:19 CST 2018
	 */
	public Float getBpfo() {
		return bpfo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf_brng.BRNG_BPFO
	 * @param bpfo  the value for skf_brng.BRNG_BPFO
	 * @mbg.generated  Tue Jun 05 15:12:19 CST 2018
	 */
	public void setBpfo(Float bpfo) {
		this.bpfo = bpfo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf_brng.BRNG_BPFI
	 * @return  the value of skf_brng.BRNG_BPFI
	 * @mbg.generated  Tue Jun 05 15:12:19 CST 2018
	 */
	public Float getBpfi() {
		return bpfi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf_brng.BRNG_BPFI
	 * @param bpfi  the value for skf_brng.BRNG_BPFI
	 * @mbg.generated  Tue Jun 05 15:12:19 CST 2018
	 */
	public void setBpfi(Float bpfi) {
		this.bpfi = bpfi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf_brng.BRNG_BSF
	 * @return  the value of skf_brng.BRNG_BSF
	 * @mbg.generated  Tue Jun 05 15:12:19 CST 2018
	 */
	public Float getBsf() {
		return bsf;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf_brng.BRNG_BSF
	 * @param bsf  the value for skf_brng.BRNG_BSF
	 * @mbg.generated  Tue Jun 05 15:12:19 CST 2018
	 */
	public void setBsf(Float bsf) {
		this.bsf = bsf;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf_brng.BRNG_FTF
	 * @return  the value of skf_brng.BRNG_FTF
	 * @mbg.generated  Tue Jun 05 15:12:19 CST 2018
	 */
	public Float getFtf() {
		return ftf;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf_brng.BRNG_FTF
	 * @param ftf  the value for skf_brng.BRNG_FTF
	 * @mbg.generated  Tue Jun 05 15:12:19 CST 2018
	 */
	public void setFtf(Float ftf) {
		this.ftf = ftf;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf_brng.BRNG_IMAGE_CODE
	 * @return  the value of skf_brng.BRNG_IMAGE_CODE
	 * @mbg.generated  Tue Jun 05 15:12:19 CST 2018
	 */
	public String getImageCode() {
		return imageCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf_brng.BRNG_IMAGE_CODE
	 * @param imageCode  the value for skf_brng.BRNG_IMAGE_CODE
	 * @mbg.generated  Tue Jun 05 15:12:19 CST 2018
	 */
	public void setImageCode(String imageCode) {
		this.imageCode = imageCode;
	}
}