package com.skf.management.model;

public class ComponentTypeModel {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKF_CPCT.CPCT_ID
	 * @mbg.generated  Fri Jun 15 17:32:09 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKF_CPCT.CPCT_NAME
	 * @mbg.generated  Fri Jun 15 17:32:09 CST 2018
	 */
	private String name;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKF_CPCT.CPCT_ID
	 * @return  the value of SKF_CPCT.CPCT_ID
	 * @mbg.generated  Fri Jun 15 17:32:09 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKF_CPCT.CPCT_ID
	 * @param id  the value for SKF_CPCT.CPCT_ID
	 * @mbg.generated  Fri Jun 15 17:32:09 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKF_CPCT.CPCT_NAME
	 * @return  the value of SKF_CPCT.CPCT_NAME
	 * @mbg.generated  Fri Jun 15 17:32:09 CST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKF_CPCT.CPCT_NAME
	 * @param name  the value for SKF_CPCT.CPCT_NAME
	 * @mbg.generated  Fri Jun 15 17:32:09 CST 2018
	 */
	public void setName(String name) {
		this.name = name;
	}
}