package com.skf.management.model;

public class ComponentTypeModel {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf_cpct.CPCT_ID
	 * @mbg.generated  Mon Jun 11 18:01:21 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf_cpct.CPCT_NAME
	 * @mbg.generated  Mon Jun 11 18:01:21 CST 2018
	 */
	private String name;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf_cpct.CPCT_ID
	 * @return  the value of skf_cpct.CPCT_ID
	 * @mbg.generated  Mon Jun 11 18:01:21 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf_cpct.CPCT_ID
	 * @param id  the value for skf_cpct.CPCT_ID
	 * @mbg.generated  Mon Jun 11 18:01:21 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf_cpct.CPCT_NAME
	 * @return  the value of skf_cpct.CPCT_NAME
	 * @mbg.generated  Mon Jun 11 18:01:21 CST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf_cpct.CPCT_NAME
	 * @param name  the value for skf_cpct.CPCT_NAME
	 * @mbg.generated  Mon Jun 11 18:01:21 CST 2018
	 */
	public void setName(String name) {
		this.name = name;
	}
}