package com.skf.management.model;

public class ComponentModel {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKF_CMPT.CMPT_CODE
	 * @mbg.generated  Tue Jun 05 16:50:42 CST 2018
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKF_CMPT.CMPT_SNSR_CODE
	 * @mbg.generated  Tue Jun 05 16:50:42 CST 2018
	 */
	private String sensorCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKF_CMPT.CMPT_CPCT_ID
	 * @mbg.generated  Tue Jun 05 16:50:42 CST 2018
	 */
	private Integer componentTypeID;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKF_CMPT.CMPT_BEARINGGEAR_CODE
	 * @mbg.generated  Tue Jun 05 16:50:42 CST 2018
	 */
	private String bearingGearCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKF_CMPT.CMPT_DANGER_LEVEL
	 * @mbg.generated  Tue Jun 05 16:50:42 CST 2018
	 */
	private Float dangerLevel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKF_CMPT.CMPT_ROTATION_SPEED
	 * @mbg.generated  Tue Jun 05 16:50:42 CST 2018
	 */
	private Float rotationSpeed;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKF_CMPT.CMPT_SPEED_TYPE
	 * @mbg.generated  Tue Jun 05 16:50:42 CST 2018
	 */
	private Integer speedType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKF_CMPT.CMPT_SCHEMA_NAME
	 * @mbg.generated  Tue Jun 05 16:50:42 CST 2018
	 */
	private String schemaName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKF_CMPT.CMPT_NODE_ID
	 * @mbg.generated  Tue Jun 05 16:50:42 CST 2018
	 */
	private Integer nodeID;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKF_CMPT.CMPT_TOTAL_VALUE
	 * @mbg.generated  Tue Jun 05 16:50:42 CST 2018
	 */
	private Float cmptTotalValue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKF_CMPT.CMPT_DEFECT_RANGE
	 * @mbg.generated  Tue Jun 05 16:50:42 CST 2018
	 */
	private Float cmptDefectRange;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKF_CMPT.CMPT_DEFECT_TYPE
	 * @mbg.generated  Tue Jun 05 16:50:42 CST 2018
	 */
	private Integer cmptDefectType;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKF_CMPT.CMPT_CODE
	 * @return  the value of SKF_CMPT.CMPT_CODE
	 * @mbg.generated  Tue Jun 05 16:50:42 CST 2018
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKF_CMPT.CMPT_CODE
	 * @param code  the value for SKF_CMPT.CMPT_CODE
	 * @mbg.generated  Tue Jun 05 16:50:42 CST 2018
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKF_CMPT.CMPT_SNSR_CODE
	 * @return  the value of SKF_CMPT.CMPT_SNSR_CODE
	 * @mbg.generated  Tue Jun 05 16:50:42 CST 2018
	 */
	public String getSensorCode() {
		return sensorCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKF_CMPT.CMPT_SNSR_CODE
	 * @param sensorCode  the value for SKF_CMPT.CMPT_SNSR_CODE
	 * @mbg.generated  Tue Jun 05 16:50:42 CST 2018
	 */
	public void setSensorCode(String sensorCode) {
		this.sensorCode = sensorCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKF_CMPT.CMPT_CPCT_ID
	 * @return  the value of SKF_CMPT.CMPT_CPCT_ID
	 * @mbg.generated  Tue Jun 05 16:50:42 CST 2018
	 */
	public Integer getComponentTypeID() {
		return componentTypeID;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKF_CMPT.CMPT_CPCT_ID
	 * @param componentTypeID  the value for SKF_CMPT.CMPT_CPCT_ID
	 * @mbg.generated  Tue Jun 05 16:50:42 CST 2018
	 */
	public void setComponentTypeID(Integer componentTypeID) {
		this.componentTypeID = componentTypeID;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKF_CMPT.CMPT_BEARINGGEAR_CODE
	 * @return  the value of SKF_CMPT.CMPT_BEARINGGEAR_CODE
	 * @mbg.generated  Tue Jun 05 16:50:42 CST 2018
	 */
	public String getBearingGearCode() {
		return bearingGearCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKF_CMPT.CMPT_BEARINGGEAR_CODE
	 * @param bearingGearCode  the value for SKF_CMPT.CMPT_BEARINGGEAR_CODE
	 * @mbg.generated  Tue Jun 05 16:50:42 CST 2018
	 */
	public void setBearingGearCode(String bearingGearCode) {
		this.bearingGearCode = bearingGearCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKF_CMPT.CMPT_DANGER_LEVEL
	 * @return  the value of SKF_CMPT.CMPT_DANGER_LEVEL
	 * @mbg.generated  Tue Jun 05 16:50:42 CST 2018
	 */
	public Float getDangerLevel() {
		return dangerLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKF_CMPT.CMPT_DANGER_LEVEL
	 * @param dangerLevel  the value for SKF_CMPT.CMPT_DANGER_LEVEL
	 * @mbg.generated  Tue Jun 05 16:50:42 CST 2018
	 */
	public void setDangerLevel(Float dangerLevel) {
		this.dangerLevel = dangerLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKF_CMPT.CMPT_ROTATION_SPEED
	 * @return  the value of SKF_CMPT.CMPT_ROTATION_SPEED
	 * @mbg.generated  Tue Jun 05 16:50:42 CST 2018
	 */
	public Float getRotationSpeed() {
		return rotationSpeed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKF_CMPT.CMPT_ROTATION_SPEED
	 * @param rotationSpeed  the value for SKF_CMPT.CMPT_ROTATION_SPEED
	 * @mbg.generated  Tue Jun 05 16:50:42 CST 2018
	 */
	public void setRotationSpeed(Float rotationSpeed) {
		this.rotationSpeed = rotationSpeed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKF_CMPT.CMPT_SPEED_TYPE
	 * @return  the value of SKF_CMPT.CMPT_SPEED_TYPE
	 * @mbg.generated  Tue Jun 05 16:50:42 CST 2018
	 */
	public Integer getSpeedType() {
		return speedType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKF_CMPT.CMPT_SPEED_TYPE
	 * @param speedType  the value for SKF_CMPT.CMPT_SPEED_TYPE
	 * @mbg.generated  Tue Jun 05 16:50:42 CST 2018
	 */
	public void setSpeedType(Integer speedType) {
		this.speedType = speedType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKF_CMPT.CMPT_SCHEMA_NAME
	 * @return  the value of SKF_CMPT.CMPT_SCHEMA_NAME
	 * @mbg.generated  Tue Jun 05 16:50:42 CST 2018
	 */
	public String getSchemaName() {
		return schemaName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKF_CMPT.CMPT_SCHEMA_NAME
	 * @param schemaName  the value for SKF_CMPT.CMPT_SCHEMA_NAME
	 * @mbg.generated  Tue Jun 05 16:50:42 CST 2018
	 */
	public void setSchemaName(String schemaName) {
		this.schemaName = schemaName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKF_CMPT.CMPT_NODE_ID
	 * @return  the value of SKF_CMPT.CMPT_NODE_ID
	 * @mbg.generated  Tue Jun 05 16:50:42 CST 2018
	 */
	public Integer getNodeID() {
		return nodeID;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKF_CMPT.CMPT_NODE_ID
	 * @param nodeID  the value for SKF_CMPT.CMPT_NODE_ID
	 * @mbg.generated  Tue Jun 05 16:50:42 CST 2018
	 */
	public void setNodeID(Integer nodeID) {
		this.nodeID = nodeID;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKF_CMPT.CMPT_TOTAL_VALUE
	 * @return  the value of SKF_CMPT.CMPT_TOTAL_VALUE
	 * @mbg.generated  Tue Jun 05 16:50:42 CST 2018
	 */
	public Float getCmptTotalValue() {
		return cmptTotalValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKF_CMPT.CMPT_TOTAL_VALUE
	 * @param cmptTotalValue  the value for SKF_CMPT.CMPT_TOTAL_VALUE
	 * @mbg.generated  Tue Jun 05 16:50:42 CST 2018
	 */
	public void setCmptTotalValue(Float cmptTotalValue) {
		this.cmptTotalValue = cmptTotalValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKF_CMPT.CMPT_DEFECT_RANGE
	 * @return  the value of SKF_CMPT.CMPT_DEFECT_RANGE
	 * @mbg.generated  Tue Jun 05 16:50:42 CST 2018
	 */
	public Float getCmptDefectRange() {
		return cmptDefectRange;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKF_CMPT.CMPT_DEFECT_RANGE
	 * @param cmptDefectRange  the value for SKF_CMPT.CMPT_DEFECT_RANGE
	 * @mbg.generated  Tue Jun 05 16:50:42 CST 2018
	 */
	public void setCmptDefectRange(Float cmptDefectRange) {
		this.cmptDefectRange = cmptDefectRange;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKF_CMPT.CMPT_DEFECT_TYPE
	 * @return  the value of SKF_CMPT.CMPT_DEFECT_TYPE
	 * @mbg.generated  Tue Jun 05 16:50:42 CST 2018
	 */
	public Integer getCmptDefectType() {
		return cmptDefectType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKF_CMPT.CMPT_DEFECT_TYPE
	 * @param cmptDefectType  the value for SKF_CMPT.CMPT_DEFECT_TYPE
	 * @mbg.generated  Tue Jun 05 16:50:42 CST 2018
	 */
	public void setCmptDefectType(Integer cmptDefectType) {
		this.cmptDefectType = cmptDefectType;
	}
}