package com.skf.management.model;

import java.util.ArrayList;
import java.util.List;

public class ComponentModelExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table skf_cmpt
	 * @mbg.generated  Thu May 31 17:15:42 CST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table skf_cmpt
	 * @mbg.generated  Thu May 31 17:15:42 CST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table skf_cmpt
	 * @mbg.generated  Thu May 31 17:15:42 CST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf_cmpt
	 * @mbg.generated  Thu May 31 17:15:42 CST 2018
	 */
	public ComponentModelExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf_cmpt
	 * @mbg.generated  Thu May 31 17:15:42 CST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf_cmpt
	 * @mbg.generated  Thu May 31 17:15:42 CST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf_cmpt
	 * @mbg.generated  Thu May 31 17:15:42 CST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf_cmpt
	 * @mbg.generated  Thu May 31 17:15:42 CST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf_cmpt
	 * @mbg.generated  Thu May 31 17:15:42 CST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf_cmpt
	 * @mbg.generated  Thu May 31 17:15:42 CST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf_cmpt
	 * @mbg.generated  Thu May 31 17:15:42 CST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf_cmpt
	 * @mbg.generated  Thu May 31 17:15:42 CST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf_cmpt
	 * @mbg.generated  Thu May 31 17:15:42 CST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table skf_cmpt
	 * @mbg.generated  Thu May 31 17:15:42 CST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table skf_cmpt
	 * @mbg.generated  Thu May 31 17:15:42 CST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andCodeIsNull() {
			addCriterion("CMPT_CODE is null");
			return (Criteria) this;
		}

		public Criteria andCodeIsNotNull() {
			addCriterion("CMPT_CODE is not null");
			return (Criteria) this;
		}

		public Criteria andCodeEqualTo(String value) {
			addCriterion("CMPT_CODE =", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotEqualTo(String value) {
			addCriterion("CMPT_CODE <>", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeGreaterThan(String value) {
			addCriterion("CMPT_CODE >", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeGreaterThanOrEqualTo(String value) {
			addCriterion("CMPT_CODE >=", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLessThan(String value) {
			addCriterion("CMPT_CODE <", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLessThanOrEqualTo(String value) {
			addCriterion("CMPT_CODE <=", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLike(String value) {
			addCriterion("CMPT_CODE like", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotLike(String value) {
			addCriterion("CMPT_CODE not like", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeIn(List<String> values) {
			addCriterion("CMPT_CODE in", values, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotIn(List<String> values) {
			addCriterion("CMPT_CODE not in", values, "code");
			return (Criteria) this;
		}

		public Criteria andCodeBetween(String value1, String value2) {
			addCriterion("CMPT_CODE between", value1, value2, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotBetween(String value1, String value2) {
			addCriterion("CMPT_CODE not between", value1, value2, "code");
			return (Criteria) this;
		}

		public Criteria andSensorCodeIsNull() {
			addCriterion("CMPT_SNSR_CODE is null");
			return (Criteria) this;
		}

		public Criteria andSensorCodeIsNotNull() {
			addCriterion("CMPT_SNSR_CODE is not null");
			return (Criteria) this;
		}

		public Criteria andSensorCodeEqualTo(String value) {
			addCriterion("CMPT_SNSR_CODE =", value, "sensorCode");
			return (Criteria) this;
		}

		public Criteria andSensorCodeNotEqualTo(String value) {
			addCriterion("CMPT_SNSR_CODE <>", value, "sensorCode");
			return (Criteria) this;
		}

		public Criteria andSensorCodeGreaterThan(String value) {
			addCriterion("CMPT_SNSR_CODE >", value, "sensorCode");
			return (Criteria) this;
		}

		public Criteria andSensorCodeGreaterThanOrEqualTo(String value) {
			addCriterion("CMPT_SNSR_CODE >=", value, "sensorCode");
			return (Criteria) this;
		}

		public Criteria andSensorCodeLessThan(String value) {
			addCriterion("CMPT_SNSR_CODE <", value, "sensorCode");
			return (Criteria) this;
		}

		public Criteria andSensorCodeLessThanOrEqualTo(String value) {
			addCriterion("CMPT_SNSR_CODE <=", value, "sensorCode");
			return (Criteria) this;
		}

		public Criteria andSensorCodeLike(String value) {
			addCriterion("CMPT_SNSR_CODE like", value, "sensorCode");
			return (Criteria) this;
		}

		public Criteria andSensorCodeNotLike(String value) {
			addCriterion("CMPT_SNSR_CODE not like", value, "sensorCode");
			return (Criteria) this;
		}

		public Criteria andSensorCodeIn(List<String> values) {
			addCriterion("CMPT_SNSR_CODE in", values, "sensorCode");
			return (Criteria) this;
		}

		public Criteria andSensorCodeNotIn(List<String> values) {
			addCriterion("CMPT_SNSR_CODE not in", values, "sensorCode");
			return (Criteria) this;
		}

		public Criteria andSensorCodeBetween(String value1, String value2) {
			addCriterion("CMPT_SNSR_CODE between", value1, value2, "sensorCode");
			return (Criteria) this;
		}

		public Criteria andSensorCodeNotBetween(String value1, String value2) {
			addCriterion("CMPT_SNSR_CODE not between", value1, value2, "sensorCode");
			return (Criteria) this;
		}

		public Criteria andComponentTypeIDIsNull() {
			addCriterion("CMPT_CPCT_ID is null");
			return (Criteria) this;
		}

		public Criteria andComponentTypeIDIsNotNull() {
			addCriterion("CMPT_CPCT_ID is not null");
			return (Criteria) this;
		}

		public Criteria andComponentTypeIDEqualTo(Integer value) {
			addCriterion("CMPT_CPCT_ID =", value, "componentTypeID");
			return (Criteria) this;
		}

		public Criteria andComponentTypeIDNotEqualTo(Integer value) {
			addCriterion("CMPT_CPCT_ID <>", value, "componentTypeID");
			return (Criteria) this;
		}

		public Criteria andComponentTypeIDGreaterThan(Integer value) {
			addCriterion("CMPT_CPCT_ID >", value, "componentTypeID");
			return (Criteria) this;
		}

		public Criteria andComponentTypeIDGreaterThanOrEqualTo(Integer value) {
			addCriterion("CMPT_CPCT_ID >=", value, "componentTypeID");
			return (Criteria) this;
		}

		public Criteria andComponentTypeIDLessThan(Integer value) {
			addCriterion("CMPT_CPCT_ID <", value, "componentTypeID");
			return (Criteria) this;
		}

		public Criteria andComponentTypeIDLessThanOrEqualTo(Integer value) {
			addCriterion("CMPT_CPCT_ID <=", value, "componentTypeID");
			return (Criteria) this;
		}

		public Criteria andComponentTypeIDIn(List<Integer> values) {
			addCriterion("CMPT_CPCT_ID in", values, "componentTypeID");
			return (Criteria) this;
		}

		public Criteria andComponentTypeIDNotIn(List<Integer> values) {
			addCriterion("CMPT_CPCT_ID not in", values, "componentTypeID");
			return (Criteria) this;
		}

		public Criteria andComponentTypeIDBetween(Integer value1, Integer value2) {
			addCriterion("CMPT_CPCT_ID between", value1, value2, "componentTypeID");
			return (Criteria) this;
		}

		public Criteria andComponentTypeIDNotBetween(Integer value1, Integer value2) {
			addCriterion("CMPT_CPCT_ID not between", value1, value2, "componentTypeID");
			return (Criteria) this;
		}

		public Criteria andBearingGearCodeIsNull() {
			addCriterion("CMPT_BEARINGGEAR_CODE is null");
			return (Criteria) this;
		}

		public Criteria andBearingGearCodeIsNotNull() {
			addCriterion("CMPT_BEARINGGEAR_CODE is not null");
			return (Criteria) this;
		}

		public Criteria andBearingGearCodeEqualTo(String value) {
			addCriterion("CMPT_BEARINGGEAR_CODE =", value, "bearingGearCode");
			return (Criteria) this;
		}

		public Criteria andBearingGearCodeNotEqualTo(String value) {
			addCriterion("CMPT_BEARINGGEAR_CODE <>", value, "bearingGearCode");
			return (Criteria) this;
		}

		public Criteria andBearingGearCodeGreaterThan(String value) {
			addCriterion("CMPT_BEARINGGEAR_CODE >", value, "bearingGearCode");
			return (Criteria) this;
		}

		public Criteria andBearingGearCodeGreaterThanOrEqualTo(String value) {
			addCriterion("CMPT_BEARINGGEAR_CODE >=", value, "bearingGearCode");
			return (Criteria) this;
		}

		public Criteria andBearingGearCodeLessThan(String value) {
			addCriterion("CMPT_BEARINGGEAR_CODE <", value, "bearingGearCode");
			return (Criteria) this;
		}

		public Criteria andBearingGearCodeLessThanOrEqualTo(String value) {
			addCriterion("CMPT_BEARINGGEAR_CODE <=", value, "bearingGearCode");
			return (Criteria) this;
		}

		public Criteria andBearingGearCodeLike(String value) {
			addCriterion("CMPT_BEARINGGEAR_CODE like", value, "bearingGearCode");
			return (Criteria) this;
		}

		public Criteria andBearingGearCodeNotLike(String value) {
			addCriterion("CMPT_BEARINGGEAR_CODE not like", value, "bearingGearCode");
			return (Criteria) this;
		}

		public Criteria andBearingGearCodeIn(List<String> values) {
			addCriterion("CMPT_BEARINGGEAR_CODE in", values, "bearingGearCode");
			return (Criteria) this;
		}

		public Criteria andBearingGearCodeNotIn(List<String> values) {
			addCriterion("CMPT_BEARINGGEAR_CODE not in", values, "bearingGearCode");
			return (Criteria) this;
		}

		public Criteria andBearingGearCodeBetween(String value1, String value2) {
			addCriterion("CMPT_BEARINGGEAR_CODE between", value1, value2, "bearingGearCode");
			return (Criteria) this;
		}

		public Criteria andBearingGearCodeNotBetween(String value1, String value2) {
			addCriterion("CMPT_BEARINGGEAR_CODE not between", value1, value2, "bearingGearCode");
			return (Criteria) this;
		}

		public Criteria andDangerLevelIsNull() {
			addCriterion("CMPT_DANGER_LEVEL is null");
			return (Criteria) this;
		}

		public Criteria andDangerLevelIsNotNull() {
			addCriterion("CMPT_DANGER_LEVEL is not null");
			return (Criteria) this;
		}

		public Criteria andDangerLevelEqualTo(Float value) {
			addCriterion("CMPT_DANGER_LEVEL =", value, "dangerLevel");
			return (Criteria) this;
		}

		public Criteria andDangerLevelNotEqualTo(Float value) {
			addCriterion("CMPT_DANGER_LEVEL <>", value, "dangerLevel");
			return (Criteria) this;
		}

		public Criteria andDangerLevelGreaterThan(Float value) {
			addCriterion("CMPT_DANGER_LEVEL >", value, "dangerLevel");
			return (Criteria) this;
		}

		public Criteria andDangerLevelGreaterThanOrEqualTo(Float value) {
			addCriterion("CMPT_DANGER_LEVEL >=", value, "dangerLevel");
			return (Criteria) this;
		}

		public Criteria andDangerLevelLessThan(Float value) {
			addCriterion("CMPT_DANGER_LEVEL <", value, "dangerLevel");
			return (Criteria) this;
		}

		public Criteria andDangerLevelLessThanOrEqualTo(Float value) {
			addCriterion("CMPT_DANGER_LEVEL <=", value, "dangerLevel");
			return (Criteria) this;
		}

		public Criteria andDangerLevelIn(List<Float> values) {
			addCriterion("CMPT_DANGER_LEVEL in", values, "dangerLevel");
			return (Criteria) this;
		}

		public Criteria andDangerLevelNotIn(List<Float> values) {
			addCriterion("CMPT_DANGER_LEVEL not in", values, "dangerLevel");
			return (Criteria) this;
		}

		public Criteria andDangerLevelBetween(Float value1, Float value2) {
			addCriterion("CMPT_DANGER_LEVEL between", value1, value2, "dangerLevel");
			return (Criteria) this;
		}

		public Criteria andDangerLevelNotBetween(Float value1, Float value2) {
			addCriterion("CMPT_DANGER_LEVEL not between", value1, value2, "dangerLevel");
			return (Criteria) this;
		}

		public Criteria andRotationSpeedIsNull() {
			addCriterion("CMPT_ROTATION_SPEED is null");
			return (Criteria) this;
		}

		public Criteria andRotationSpeedIsNotNull() {
			addCriterion("CMPT_ROTATION_SPEED is not null");
			return (Criteria) this;
		}

		public Criteria andRotationSpeedEqualTo(Float value) {
			addCriterion("CMPT_ROTATION_SPEED =", value, "rotationSpeed");
			return (Criteria) this;
		}

		public Criteria andRotationSpeedNotEqualTo(Float value) {
			addCriterion("CMPT_ROTATION_SPEED <>", value, "rotationSpeed");
			return (Criteria) this;
		}

		public Criteria andRotationSpeedGreaterThan(Float value) {
			addCriterion("CMPT_ROTATION_SPEED >", value, "rotationSpeed");
			return (Criteria) this;
		}

		public Criteria andRotationSpeedGreaterThanOrEqualTo(Float value) {
			addCriterion("CMPT_ROTATION_SPEED >=", value, "rotationSpeed");
			return (Criteria) this;
		}

		public Criteria andRotationSpeedLessThan(Float value) {
			addCriterion("CMPT_ROTATION_SPEED <", value, "rotationSpeed");
			return (Criteria) this;
		}

		public Criteria andRotationSpeedLessThanOrEqualTo(Float value) {
			addCriterion("CMPT_ROTATION_SPEED <=", value, "rotationSpeed");
			return (Criteria) this;
		}

		public Criteria andRotationSpeedIn(List<Float> values) {
			addCriterion("CMPT_ROTATION_SPEED in", values, "rotationSpeed");
			return (Criteria) this;
		}

		public Criteria andRotationSpeedNotIn(List<Float> values) {
			addCriterion("CMPT_ROTATION_SPEED not in", values, "rotationSpeed");
			return (Criteria) this;
		}

		public Criteria andRotationSpeedBetween(Float value1, Float value2) {
			addCriterion("CMPT_ROTATION_SPEED between", value1, value2, "rotationSpeed");
			return (Criteria) this;
		}

		public Criteria andRotationSpeedNotBetween(Float value1, Float value2) {
			addCriterion("CMPT_ROTATION_SPEED not between", value1, value2, "rotationSpeed");
			return (Criteria) this;
		}

		public Criteria andSpeedTypeIsNull() {
			addCriterion("CMPT_SPEED_TYPE is null");
			return (Criteria) this;
		}

		public Criteria andSpeedTypeIsNotNull() {
			addCriterion("CMPT_SPEED_TYPE is not null");
			return (Criteria) this;
		}

		public Criteria andSpeedTypeEqualTo(Integer value) {
			addCriterion("CMPT_SPEED_TYPE =", value, "speedType");
			return (Criteria) this;
		}

		public Criteria andSpeedTypeNotEqualTo(Integer value) {
			addCriterion("CMPT_SPEED_TYPE <>", value, "speedType");
			return (Criteria) this;
		}

		public Criteria andSpeedTypeGreaterThan(Integer value) {
			addCriterion("CMPT_SPEED_TYPE >", value, "speedType");
			return (Criteria) this;
		}

		public Criteria andSpeedTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("CMPT_SPEED_TYPE >=", value, "speedType");
			return (Criteria) this;
		}

		public Criteria andSpeedTypeLessThan(Integer value) {
			addCriterion("CMPT_SPEED_TYPE <", value, "speedType");
			return (Criteria) this;
		}

		public Criteria andSpeedTypeLessThanOrEqualTo(Integer value) {
			addCriterion("CMPT_SPEED_TYPE <=", value, "speedType");
			return (Criteria) this;
		}

		public Criteria andSpeedTypeIn(List<Integer> values) {
			addCriterion("CMPT_SPEED_TYPE in", values, "speedType");
			return (Criteria) this;
		}

		public Criteria andSpeedTypeNotIn(List<Integer> values) {
			addCriterion("CMPT_SPEED_TYPE not in", values, "speedType");
			return (Criteria) this;
		}

		public Criteria andSpeedTypeBetween(Integer value1, Integer value2) {
			addCriterion("CMPT_SPEED_TYPE between", value1, value2, "speedType");
			return (Criteria) this;
		}

		public Criteria andSpeedTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("CMPT_SPEED_TYPE not between", value1, value2, "speedType");
			return (Criteria) this;
		}

		public Criteria andSchemaNameIsNull() {
			addCriterion("CMPT_SCHEMA_NAME is null");
			return (Criteria) this;
		}

		public Criteria andSchemaNameIsNotNull() {
			addCriterion("CMPT_SCHEMA_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andSchemaNameEqualTo(String value) {
			addCriterion("CMPT_SCHEMA_NAME =", value, "schemaName");
			return (Criteria) this;
		}

		public Criteria andSchemaNameNotEqualTo(String value) {
			addCriterion("CMPT_SCHEMA_NAME <>", value, "schemaName");
			return (Criteria) this;
		}

		public Criteria andSchemaNameGreaterThan(String value) {
			addCriterion("CMPT_SCHEMA_NAME >", value, "schemaName");
			return (Criteria) this;
		}

		public Criteria andSchemaNameGreaterThanOrEqualTo(String value) {
			addCriterion("CMPT_SCHEMA_NAME >=", value, "schemaName");
			return (Criteria) this;
		}

		public Criteria andSchemaNameLessThan(String value) {
			addCriterion("CMPT_SCHEMA_NAME <", value, "schemaName");
			return (Criteria) this;
		}

		public Criteria andSchemaNameLessThanOrEqualTo(String value) {
			addCriterion("CMPT_SCHEMA_NAME <=", value, "schemaName");
			return (Criteria) this;
		}

		public Criteria andSchemaNameLike(String value) {
			addCriterion("CMPT_SCHEMA_NAME like", value, "schemaName");
			return (Criteria) this;
		}

		public Criteria andSchemaNameNotLike(String value) {
			addCriterion("CMPT_SCHEMA_NAME not like", value, "schemaName");
			return (Criteria) this;
		}

		public Criteria andSchemaNameIn(List<String> values) {
			addCriterion("CMPT_SCHEMA_NAME in", values, "schemaName");
			return (Criteria) this;
		}

		public Criteria andSchemaNameNotIn(List<String> values) {
			addCriterion("CMPT_SCHEMA_NAME not in", values, "schemaName");
			return (Criteria) this;
		}

		public Criteria andSchemaNameBetween(String value1, String value2) {
			addCriterion("CMPT_SCHEMA_NAME between", value1, value2, "schemaName");
			return (Criteria) this;
		}

		public Criteria andSchemaNameNotBetween(String value1, String value2) {
			addCriterion("CMPT_SCHEMA_NAME not between", value1, value2, "schemaName");
			return (Criteria) this;
		}

		public Criteria andNodeIDIsNull() {
			addCriterion("CMPT_NODE_ID is null");
			return (Criteria) this;
		}

		public Criteria andNodeIDIsNotNull() {
			addCriterion("CMPT_NODE_ID is not null");
			return (Criteria) this;
		}

		public Criteria andNodeIDEqualTo(Integer value) {
			addCriterion("CMPT_NODE_ID =", value, "nodeID");
			return (Criteria) this;
		}

		public Criteria andNodeIDNotEqualTo(Integer value) {
			addCriterion("CMPT_NODE_ID <>", value, "nodeID");
			return (Criteria) this;
		}

		public Criteria andNodeIDGreaterThan(Integer value) {
			addCriterion("CMPT_NODE_ID >", value, "nodeID");
			return (Criteria) this;
		}

		public Criteria andNodeIDGreaterThanOrEqualTo(Integer value) {
			addCriterion("CMPT_NODE_ID >=", value, "nodeID");
			return (Criteria) this;
		}

		public Criteria andNodeIDLessThan(Integer value) {
			addCriterion("CMPT_NODE_ID <", value, "nodeID");
			return (Criteria) this;
		}

		public Criteria andNodeIDLessThanOrEqualTo(Integer value) {
			addCriterion("CMPT_NODE_ID <=", value, "nodeID");
			return (Criteria) this;
		}

		public Criteria andNodeIDIn(List<Integer> values) {
			addCriterion("CMPT_NODE_ID in", values, "nodeID");
			return (Criteria) this;
		}

		public Criteria andNodeIDNotIn(List<Integer> values) {
			addCriterion("CMPT_NODE_ID not in", values, "nodeID");
			return (Criteria) this;
		}

		public Criteria andNodeIDBetween(Integer value1, Integer value2) {
			addCriterion("CMPT_NODE_ID between", value1, value2, "nodeID");
			return (Criteria) this;
		}

		public Criteria andNodeIDNotBetween(Integer value1, Integer value2) {
			addCriterion("CMPT_NODE_ID not between", value1, value2, "nodeID");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table skf_cmpt
	 * @mbg.generated  Thu May 31 17:15:42 CST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table skf_cmpt
     *
     * @mbg.generated do_not_delete_during_merge Fri May 11 17:49:13 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}