package com.skf.management.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DboBearingModelExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.Bearing
     *
     * @mbg.generated Mon Jun 11 17:10:37 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.Bearing
     *
     * @mbg.generated Mon Jun 11 17:10:37 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.Bearing
     *
     * @mbg.generated Mon Jun 11 17:10:37 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Bearing
     *
     * @mbg.generated Mon Jun 11 17:10:37 CST 2018
     */
    public DboBearingModelExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Bearing
     *
     * @mbg.generated Mon Jun 11 17:10:37 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Bearing
     *
     * @mbg.generated Mon Jun 11 17:10:37 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Bearing
     *
     * @mbg.generated Mon Jun 11 17:10:37 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Bearing
     *
     * @mbg.generated Mon Jun 11 17:10:37 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Bearing
     *
     * @mbg.generated Mon Jun 11 17:10:37 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Bearing
     *
     * @mbg.generated Mon Jun 11 17:10:37 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Bearing
     *
     * @mbg.generated Mon Jun 11 17:10:37 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Bearing
     *
     * @mbg.generated Mon Jun 11 17:10:37 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Bearing
     *
     * @mbg.generated Mon Jun 11 17:10:37 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.Bearing
     *
     * @mbg.generated Mon Jun 11 17:10:37 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.Bearing
     *
     * @mbg.generated Mon Jun 11 17:10:37 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andModelNumberIsNull() {
            addCriterion("ModelNumber is null");
            return (Criteria) this;
        }

        public Criteria andModelNumberIsNotNull() {
            addCriterion("ModelNumber is not null");
            return (Criteria) this;
        }

        public Criteria andModelNumberEqualTo(String value) {
            addCriterion("ModelNumber =", value, "modelNumber");
            return (Criteria) this;
        }

        public Criteria andModelNumberNotEqualTo(String value) {
            addCriterion("ModelNumber <>", value, "modelNumber");
            return (Criteria) this;
        }

        public Criteria andModelNumberGreaterThan(String value) {
            addCriterion("ModelNumber >", value, "modelNumber");
            return (Criteria) this;
        }

        public Criteria andModelNumberGreaterThanOrEqualTo(String value) {
            addCriterion("ModelNumber >=", value, "modelNumber");
            return (Criteria) this;
        }

        public Criteria andModelNumberLessThan(String value) {
            addCriterion("ModelNumber <", value, "modelNumber");
            return (Criteria) this;
        }

        public Criteria andModelNumberLessThanOrEqualTo(String value) {
            addCriterion("ModelNumber <=", value, "modelNumber");
            return (Criteria) this;
        }

        public Criteria andModelNumberLike(String value) {
            addCriterion("ModelNumber like", value, "modelNumber");
            return (Criteria) this;
        }

        public Criteria andModelNumberNotLike(String value) {
            addCriterion("ModelNumber not like", value, "modelNumber");
            return (Criteria) this;
        }

        public Criteria andModelNumberIn(List<String> values) {
            addCriterion("ModelNumber in", values, "modelNumber");
            return (Criteria) this;
        }

        public Criteria andModelNumberNotIn(List<String> values) {
            addCriterion("ModelNumber not in", values, "modelNumber");
            return (Criteria) this;
        }

        public Criteria andModelNumberBetween(String value1, String value2) {
            addCriterion("ModelNumber between", value1, value2, "modelNumber");
            return (Criteria) this;
        }

        public Criteria andModelNumberNotBetween(String value1, String value2) {
            addCriterion("ModelNumber not between", value1, value2, "modelNumber");
            return (Criteria) this;
        }

        public Criteria andManufactureIsNull() {
            addCriterion("Manufacture is null");
            return (Criteria) this;
        }

        public Criteria andManufactureIsNotNull() {
            addCriterion("Manufacture is not null");
            return (Criteria) this;
        }

        public Criteria andManufactureEqualTo(String value) {
            addCriterion("Manufacture =", value, "manufacture");
            return (Criteria) this;
        }

        public Criteria andManufactureNotEqualTo(String value) {
            addCriterion("Manufacture <>", value, "manufacture");
            return (Criteria) this;
        }

        public Criteria andManufactureGreaterThan(String value) {
            addCriterion("Manufacture >", value, "manufacture");
            return (Criteria) this;
        }

        public Criteria andManufactureGreaterThanOrEqualTo(String value) {
            addCriterion("Manufacture >=", value, "manufacture");
            return (Criteria) this;
        }

        public Criteria andManufactureLessThan(String value) {
            addCriterion("Manufacture <", value, "manufacture");
            return (Criteria) this;
        }

        public Criteria andManufactureLessThanOrEqualTo(String value) {
            addCriterion("Manufacture <=", value, "manufacture");
            return (Criteria) this;
        }

        public Criteria andManufactureLike(String value) {
            addCriterion("Manufacture like", value, "manufacture");
            return (Criteria) this;
        }

        public Criteria andManufactureNotLike(String value) {
            addCriterion("Manufacture not like", value, "manufacture");
            return (Criteria) this;
        }

        public Criteria andManufactureIn(List<String> values) {
            addCriterion("Manufacture in", values, "manufacture");
            return (Criteria) this;
        }

        public Criteria andManufactureNotIn(List<String> values) {
            addCriterion("Manufacture not in", values, "manufacture");
            return (Criteria) this;
        }

        public Criteria andManufactureBetween(String value1, String value2) {
            addCriterion("Manufacture between", value1, value2, "manufacture");
            return (Criteria) this;
        }

        public Criteria andManufactureNotBetween(String value1, String value2) {
            addCriterion("Manufacture not between", value1, value2, "manufacture");
            return (Criteria) this;
        }

        public Criteria andBpfoIsNull() {
            addCriterion("BPFO is null");
            return (Criteria) this;
        }

        public Criteria andBpfoIsNotNull() {
            addCriterion("BPFO is not null");
            return (Criteria) this;
        }

        public Criteria andBpfoEqualTo(Float value) {
            addCriterion("BPFO =", value, "bpfo");
            return (Criteria) this;
        }

        public Criteria andBpfoNotEqualTo(Float value) {
            addCriterion("BPFO <>", value, "bpfo");
            return (Criteria) this;
        }

        public Criteria andBpfoGreaterThan(Float value) {
            addCriterion("BPFO >", value, "bpfo");
            return (Criteria) this;
        }

        public Criteria andBpfoGreaterThanOrEqualTo(Float value) {
            addCriterion("BPFO >=", value, "bpfo");
            return (Criteria) this;
        }

        public Criteria andBpfoLessThan(Float value) {
            addCriterion("BPFO <", value, "bpfo");
            return (Criteria) this;
        }

        public Criteria andBpfoLessThanOrEqualTo(Float value) {
            addCriterion("BPFO <=", value, "bpfo");
            return (Criteria) this;
        }

        public Criteria andBpfoIn(List<Float> values) {
            addCriterion("BPFO in", values, "bpfo");
            return (Criteria) this;
        }

        public Criteria andBpfoNotIn(List<Float> values) {
            addCriterion("BPFO not in", values, "bpfo");
            return (Criteria) this;
        }

        public Criteria andBpfoBetween(Float value1, Float value2) {
            addCriterion("BPFO between", value1, value2, "bpfo");
            return (Criteria) this;
        }

        public Criteria andBpfoNotBetween(Float value1, Float value2) {
            addCriterion("BPFO not between", value1, value2, "bpfo");
            return (Criteria) this;
        }

        public Criteria andBpfiIsNull() {
            addCriterion("BPFI is null");
            return (Criteria) this;
        }

        public Criteria andBpfiIsNotNull() {
            addCriterion("BPFI is not null");
            return (Criteria) this;
        }

        public Criteria andBpfiEqualTo(Float value) {
            addCriterion("BPFI =", value, "bpfi");
            return (Criteria) this;
        }

        public Criteria andBpfiNotEqualTo(Float value) {
            addCriterion("BPFI <>", value, "bpfi");
            return (Criteria) this;
        }

        public Criteria andBpfiGreaterThan(Float value) {
            addCriterion("BPFI >", value, "bpfi");
            return (Criteria) this;
        }

        public Criteria andBpfiGreaterThanOrEqualTo(Float value) {
            addCriterion("BPFI >=", value, "bpfi");
            return (Criteria) this;
        }

        public Criteria andBpfiLessThan(Float value) {
            addCriterion("BPFI <", value, "bpfi");
            return (Criteria) this;
        }

        public Criteria andBpfiLessThanOrEqualTo(Float value) {
            addCriterion("BPFI <=", value, "bpfi");
            return (Criteria) this;
        }

        public Criteria andBpfiIn(List<Float> values) {
            addCriterion("BPFI in", values, "bpfi");
            return (Criteria) this;
        }

        public Criteria andBpfiNotIn(List<Float> values) {
            addCriterion("BPFI not in", values, "bpfi");
            return (Criteria) this;
        }

        public Criteria andBpfiBetween(Float value1, Float value2) {
            addCriterion("BPFI between", value1, value2, "bpfi");
            return (Criteria) this;
        }

        public Criteria andBpfiNotBetween(Float value1, Float value2) {
            addCriterion("BPFI not between", value1, value2, "bpfi");
            return (Criteria) this;
        }

        public Criteria andBsfIsNull() {
            addCriterion("BSF is null");
            return (Criteria) this;
        }

        public Criteria andBsfIsNotNull() {
            addCriterion("BSF is not null");
            return (Criteria) this;
        }

        public Criteria andBsfEqualTo(Float value) {
            addCriterion("BSF =", value, "bsf");
            return (Criteria) this;
        }

        public Criteria andBsfNotEqualTo(Float value) {
            addCriterion("BSF <>", value, "bsf");
            return (Criteria) this;
        }

        public Criteria andBsfGreaterThan(Float value) {
            addCriterion("BSF >", value, "bsf");
            return (Criteria) this;
        }

        public Criteria andBsfGreaterThanOrEqualTo(Float value) {
            addCriterion("BSF >=", value, "bsf");
            return (Criteria) this;
        }

        public Criteria andBsfLessThan(Float value) {
            addCriterion("BSF <", value, "bsf");
            return (Criteria) this;
        }

        public Criteria andBsfLessThanOrEqualTo(Float value) {
            addCriterion("BSF <=", value, "bsf");
            return (Criteria) this;
        }

        public Criteria andBsfIn(List<Float> values) {
            addCriterion("BSF in", values, "bsf");
            return (Criteria) this;
        }

        public Criteria andBsfNotIn(List<Float> values) {
            addCriterion("BSF not in", values, "bsf");
            return (Criteria) this;
        }

        public Criteria andBsfBetween(Float value1, Float value2) {
            addCriterion("BSF between", value1, value2, "bsf");
            return (Criteria) this;
        }

        public Criteria andBsfNotBetween(Float value1, Float value2) {
            addCriterion("BSF not between", value1, value2, "bsf");
            return (Criteria) this;
        }

        public Criteria andFtfIsNull() {
            addCriterion("FTF is null");
            return (Criteria) this;
        }

        public Criteria andFtfIsNotNull() {
            addCriterion("FTF is not null");
            return (Criteria) this;
        }

        public Criteria andFtfEqualTo(Float value) {
            addCriterion("FTF =", value, "ftf");
            return (Criteria) this;
        }

        public Criteria andFtfNotEqualTo(Float value) {
            addCriterion("FTF <>", value, "ftf");
            return (Criteria) this;
        }

        public Criteria andFtfGreaterThan(Float value) {
            addCriterion("FTF >", value, "ftf");
            return (Criteria) this;
        }

        public Criteria andFtfGreaterThanOrEqualTo(Float value) {
            addCriterion("FTF >=", value, "ftf");
            return (Criteria) this;
        }

        public Criteria andFtfLessThan(Float value) {
            addCriterion("FTF <", value, "ftf");
            return (Criteria) this;
        }

        public Criteria andFtfLessThanOrEqualTo(Float value) {
            addCriterion("FTF <=", value, "ftf");
            return (Criteria) this;
        }

        public Criteria andFtfIn(List<Float> values) {
            addCriterion("FTF in", values, "ftf");
            return (Criteria) this;
        }

        public Criteria andFtfNotIn(List<Float> values) {
            addCriterion("FTF not in", values, "ftf");
            return (Criteria) this;
        }

        public Criteria andFtfBetween(Float value1, Float value2) {
            addCriterion("FTF between", value1, value2, "ftf");
            return (Criteria) this;
        }

        public Criteria andFtfNotBetween(Float value1, Float value2) {
            addCriterion("FTF not between", value1, value2, "ftf");
            return (Criteria) this;
        }

        public Criteria andGscguidIsNull() {
            addCriterion("GSCGuid is null");
            return (Criteria) this;
        }

        public Criteria andGscguidIsNotNull() {
            addCriterion("GSCGuid is not null");
            return (Criteria) this;
        }

        public Criteria andGscguidEqualTo(String value) {
            addCriterion("GSCGuid =", value, "gscguid");
            return (Criteria) this;
        }

        public Criteria andGscguidNotEqualTo(String value) {
            addCriterion("GSCGuid <>", value, "gscguid");
            return (Criteria) this;
        }

        public Criteria andGscguidGreaterThan(String value) {
            addCriterion("GSCGuid >", value, "gscguid");
            return (Criteria) this;
        }

        public Criteria andGscguidGreaterThanOrEqualTo(String value) {
            addCriterion("GSCGuid >=", value, "gscguid");
            return (Criteria) this;
        }

        public Criteria andGscguidLessThan(String value) {
            addCriterion("GSCGuid <", value, "gscguid");
            return (Criteria) this;
        }

        public Criteria andGscguidLessThanOrEqualTo(String value) {
            addCriterion("GSCGuid <=", value, "gscguid");
            return (Criteria) this;
        }

        public Criteria andGscguidLike(String value) {
            addCriterion("GSCGuid like", value, "gscguid");
            return (Criteria) this;
        }

        public Criteria andGscguidNotLike(String value) {
            addCriterion("GSCGuid not like", value, "gscguid");
            return (Criteria) this;
        }

        public Criteria andGscguidIn(List<String> values) {
            addCriterion("GSCGuid in", values, "gscguid");
            return (Criteria) this;
        }

        public Criteria andGscguidNotIn(List<String> values) {
            addCriterion("GSCGuid not in", values, "gscguid");
            return (Criteria) this;
        }

        public Criteria andGscguidBetween(String value1, String value2) {
            addCriterion("GSCGuid between", value1, value2, "gscguid");
            return (Criteria) this;
        }

        public Criteria andGscguidNotBetween(String value1, String value2) {
            addCriterion("GSCGuid not between", value1, value2, "gscguid");
            return (Criteria) this;
        }

        public Criteria andGscmodifieddateIsNull() {
            addCriterion("GSCModifiedDate is null");
            return (Criteria) this;
        }

        public Criteria andGscmodifieddateIsNotNull() {
            addCriterion("GSCModifiedDate is not null");
            return (Criteria) this;
        }

        public Criteria andGscmodifieddateEqualTo(Date value) {
            addCriterion("GSCModifiedDate =", value, "gscmodifieddate");
            return (Criteria) this;
        }

        public Criteria andGscmodifieddateNotEqualTo(Date value) {
            addCriterion("GSCModifiedDate <>", value, "gscmodifieddate");
            return (Criteria) this;
        }

        public Criteria andGscmodifieddateGreaterThan(Date value) {
            addCriterion("GSCModifiedDate >", value, "gscmodifieddate");
            return (Criteria) this;
        }

        public Criteria andGscmodifieddateGreaterThanOrEqualTo(Date value) {
            addCriterion("GSCModifiedDate >=", value, "gscmodifieddate");
            return (Criteria) this;
        }

        public Criteria andGscmodifieddateLessThan(Date value) {
            addCriterion("GSCModifiedDate <", value, "gscmodifieddate");
            return (Criteria) this;
        }

        public Criteria andGscmodifieddateLessThanOrEqualTo(Date value) {
            addCriterion("GSCModifiedDate <=", value, "gscmodifieddate");
            return (Criteria) this;
        }

        public Criteria andGscmodifieddateIn(List<Date> values) {
            addCriterion("GSCModifiedDate in", values, "gscmodifieddate");
            return (Criteria) this;
        }

        public Criteria andGscmodifieddateNotIn(List<Date> values) {
            addCriterion("GSCModifiedDate not in", values, "gscmodifieddate");
            return (Criteria) this;
        }

        public Criteria andGscmodifieddateBetween(Date value1, Date value2) {
            addCriterion("GSCModifiedDate between", value1, value2, "gscmodifieddate");
            return (Criteria) this;
        }

        public Criteria andGscmodifieddateNotBetween(Date value1, Date value2) {
            addCriterion("GSCModifiedDate not between", value1, value2, "gscmodifieddate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.Bearing
     *
     * @mbg.generated do_not_delete_during_merge Mon Jun 11 17:10:37 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.Bearing
     *
     * @mbg.generated Mon Jun 11 17:10:37 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}