package com.skf.management.model;

public class DboBearingModelKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.Bearing.ModelNumber
     *
     * @mbg.generated Mon Jun 11 17:10:37 CST 2018
     */
    private String modelNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.Bearing.Manufacture
     *
     * @mbg.generated Mon Jun 11 17:10:37 CST 2018
     */
    private String manufacture;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.Bearing.ModelNumber
     *
     * @return the value of dbo.Bearing.ModelNumber
     *
     * @mbg.generated Mon Jun 11 17:10:37 CST 2018
     */
    public String getModelNumber() {
        return modelNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.Bearing.ModelNumber
     *
     * @param modelNumber the value for dbo.Bearing.ModelNumber
     *
     * @mbg.generated Mon Jun 11 17:10:37 CST 2018
     */
    public void setModelNumber(String modelNumber) {
        this.modelNumber = modelNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.Bearing.Manufacture
     *
     * @return the value of dbo.Bearing.Manufacture
     *
     * @mbg.generated Mon Jun 11 17:10:37 CST 2018
     */
    public String getManufacture() {
        return manufacture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.Bearing.Manufacture
     *
     * @param manufacture the value for dbo.Bearing.Manufacture
     *
     * @mbg.generated Mon Jun 11 17:10:37 CST 2018
     */
    public void setManufacture(String manufacture) {
        this.manufacture = manufacture;
    }
}