package com.skf.management.model;

import java.util.Date;

public class DboBearingModel extends DboBearingModelKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.Bearing.BPFO
     *
     * @mbg.generated Mon Jun 11 17:10:37 CST 2018
     */
    private Float bpfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.Bearing.BPFI
     *
     * @mbg.generated Mon Jun 11 17:10:37 CST 2018
     */
    private Float bpfi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.Bearing.BSF
     *
     * @mbg.generated Mon Jun 11 17:10:37 CST 2018
     */
    private Float bsf;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.Bearing.FTF
     *
     * @mbg.generated Mon Jun 11 17:10:37 CST 2018
     */
    private Float ftf;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.Bearing.GSCGuid
     *
     * @mbg.generated Mon Jun 11 17:10:37 CST 2018
     */
    private String gscguid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.Bearing.GSCModifiedDate
     *
     * @mbg.generated Mon Jun 11 17:10:37 CST 2018
     */
    private Date gscmodifieddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.Bearing.Description
     *
     * @mbg.generated Mon Jun 11 17:10:37 CST 2018
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.Bearing.BPFO
     *
     * @return the value of dbo.Bearing.BPFO
     *
     * @mbg.generated Mon Jun 11 17:10:37 CST 2018
     */
    public Float getBpfo() {
        return bpfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.Bearing.BPFO
     *
     * @param bpfo the value for dbo.Bearing.BPFO
     *
     * @mbg.generated Mon Jun 11 17:10:37 CST 2018
     */
    public void setBpfo(Float bpfo) {
        this.bpfo = bpfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.Bearing.BPFI
     *
     * @return the value of dbo.Bearing.BPFI
     *
     * @mbg.generated Mon Jun 11 17:10:37 CST 2018
     */
    public Float getBpfi() {
        return bpfi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.Bearing.BPFI
     *
     * @param bpfi the value for dbo.Bearing.BPFI
     *
     * @mbg.generated Mon Jun 11 17:10:37 CST 2018
     */
    public void setBpfi(Float bpfi) {
        this.bpfi = bpfi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.Bearing.BSF
     *
     * @return the value of dbo.Bearing.BSF
     *
     * @mbg.generated Mon Jun 11 17:10:37 CST 2018
     */
    public Float getBsf() {
        return bsf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.Bearing.BSF
     *
     * @param bsf the value for dbo.Bearing.BSF
     *
     * @mbg.generated Mon Jun 11 17:10:37 CST 2018
     */
    public void setBsf(Float bsf) {
        this.bsf = bsf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.Bearing.FTF
     *
     * @return the value of dbo.Bearing.FTF
     *
     * @mbg.generated Mon Jun 11 17:10:37 CST 2018
     */
    public Float getFtf() {
        return ftf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.Bearing.FTF
     *
     * @param ftf the value for dbo.Bearing.FTF
     *
     * @mbg.generated Mon Jun 11 17:10:37 CST 2018
     */
    public void setFtf(Float ftf) {
        this.ftf = ftf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.Bearing.GSCGuid
     *
     * @return the value of dbo.Bearing.GSCGuid
     *
     * @mbg.generated Mon Jun 11 17:10:37 CST 2018
     */
    public String getGscguid() {
        return gscguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.Bearing.GSCGuid
     *
     * @param gscguid the value for dbo.Bearing.GSCGuid
     *
     * @mbg.generated Mon Jun 11 17:10:37 CST 2018
     */
    public void setGscguid(String gscguid) {
        this.gscguid = gscguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.Bearing.GSCModifiedDate
     *
     * @return the value of dbo.Bearing.GSCModifiedDate
     *
     * @mbg.generated Mon Jun 11 17:10:37 CST 2018
     */
    public Date getGscmodifieddate() {
        return gscmodifieddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.Bearing.GSCModifiedDate
     *
     * @param gscmodifieddate the value for dbo.Bearing.GSCModifiedDate
     *
     * @mbg.generated Mon Jun 11 17:10:37 CST 2018
     */
    public void setGscmodifieddate(Date gscmodifieddate) {
        this.gscmodifieddate = gscmodifieddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.Bearing.Description
     *
     * @return the value of dbo.Bearing.Description
     *
     * @mbg.generated Mon Jun 11 17:10:37 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.Bearing.Description
     *
     * @param description the value for dbo.Bearing.Description
     *
     * @mbg.generated Mon Jun 11 17:10:37 CST 2018
     */
    public void setDescription(String description) {
        this.description = description;
    }
}