package com.skf.management.model;

public class EquipmentTypeModel {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKF_QPMT_TYPE.QPTP_TYPE_CODE
	 * @mbg.generated  Fri Jun 15 18:04:35 CST 2018
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKF_QPMT_TYPE.QPTP_CSTM_CODE
	 * @mbg.generated  Fri Jun 15 18:04:35 CST 2018
	 */
	private String customerCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKF_QPMT_TYPE.QPTP_TYPE_NAME
	 * @mbg.generated  Fri Jun 15 18:04:35 CST 2018
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKF_QPMT_TYPE.QPTP_TYPE_DESC
	 * @mbg.generated  Fri Jun 15 18:04:35 CST 2018
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKF_QPMT_TYPE.QPTP_TYPE_IMG
	 * @mbg.generated  Fri Jun 15 18:04:35 CST 2018
	 */
	private String img;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKF_QPMT_TYPE.QPTP_TYPE_CODE
	 * @return  the value of SKF_QPMT_TYPE.QPTP_TYPE_CODE
	 * @mbg.generated  Fri Jun 15 18:04:35 CST 2018
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKF_QPMT_TYPE.QPTP_TYPE_CODE
	 * @param code  the value for SKF_QPMT_TYPE.QPTP_TYPE_CODE
	 * @mbg.generated  Fri Jun 15 18:04:35 CST 2018
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKF_QPMT_TYPE.QPTP_CSTM_CODE
	 * @return  the value of SKF_QPMT_TYPE.QPTP_CSTM_CODE
	 * @mbg.generated  Fri Jun 15 18:04:35 CST 2018
	 */
	public String getCustomerCode() {
		return customerCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKF_QPMT_TYPE.QPTP_CSTM_CODE
	 * @param customerCode  the value for SKF_QPMT_TYPE.QPTP_CSTM_CODE
	 * @mbg.generated  Fri Jun 15 18:04:35 CST 2018
	 */
	public void setCustomerCode(String customerCode) {
		this.customerCode = customerCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKF_QPMT_TYPE.QPTP_TYPE_NAME
	 * @return  the value of SKF_QPMT_TYPE.QPTP_TYPE_NAME
	 * @mbg.generated  Fri Jun 15 18:04:35 CST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKF_QPMT_TYPE.QPTP_TYPE_NAME
	 * @param name  the value for SKF_QPMT_TYPE.QPTP_TYPE_NAME
	 * @mbg.generated  Fri Jun 15 18:04:35 CST 2018
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKF_QPMT_TYPE.QPTP_TYPE_DESC
	 * @return  the value of SKF_QPMT_TYPE.QPTP_TYPE_DESC
	 * @mbg.generated  Fri Jun 15 18:04:35 CST 2018
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKF_QPMT_TYPE.QPTP_TYPE_DESC
	 * @param description  the value for SKF_QPMT_TYPE.QPTP_TYPE_DESC
	 * @mbg.generated  Fri Jun 15 18:04:35 CST 2018
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKF_QPMT_TYPE.QPTP_TYPE_IMG
	 * @return  the value of SKF_QPMT_TYPE.QPTP_TYPE_IMG
	 * @mbg.generated  Fri Jun 15 18:04:35 CST 2018
	 */
	public String getImg() {
		return img;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKF_QPMT_TYPE.QPTP_TYPE_IMG
	 * @param img  the value for SKF_QPMT_TYPE.QPTP_TYPE_IMG
	 * @mbg.generated  Fri Jun 15 18:04:35 CST 2018
	 */
	public void setImg(String img) {
		this.img = img;
	}
}