package com.skf.management.model;

public class GearModel {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKF_GEAR.GEAR_CODE
	 * @mbg.generated  Fri Jun 15 17:32:09 CST 2018
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKF_GEAR.GEAR_MODEL_NUMBER
	 * @mbg.generated  Fri Jun 15 17:32:09 CST 2018
	 */
	private String modelNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKF_GEAR.GEAR_MANUFACTURE
	 * @mbg.generated  Fri Jun 15 17:32:09 CST 2018
	 */
	private String manufacture;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKF_GEAR.GEAR_DESCRIPTION
	 * @mbg.generated  Fri Jun 15 17:32:09 CST 2018
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKF_GEAR.GEAR_MESHING_FREQUENCY
	 * @mbg.generated  Fri Jun 15 17:32:09 CST 2018
	 */
	private Float meshingFrequency;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKF_GEAR.GEAR_IMAGE_CODE
	 * @mbg.generated  Fri Jun 15 17:32:09 CST 2018
	 */
	private String imageCode;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKF_GEAR.GEAR_CODE
	 * @return  the value of SKF_GEAR.GEAR_CODE
	 * @mbg.generated  Fri Jun 15 17:32:09 CST 2018
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKF_GEAR.GEAR_CODE
	 * @param code  the value for SKF_GEAR.GEAR_CODE
	 * @mbg.generated  Fri Jun 15 17:32:09 CST 2018
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKF_GEAR.GEAR_MODEL_NUMBER
	 * @return  the value of SKF_GEAR.GEAR_MODEL_NUMBER
	 * @mbg.generated  Fri Jun 15 17:32:09 CST 2018
	 */
	public String getModelNumber() {
		return modelNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKF_GEAR.GEAR_MODEL_NUMBER
	 * @param modelNumber  the value for SKF_GEAR.GEAR_MODEL_NUMBER
	 * @mbg.generated  Fri Jun 15 17:32:09 CST 2018
	 */
	public void setModelNumber(String modelNumber) {
		this.modelNumber = modelNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKF_GEAR.GEAR_MANUFACTURE
	 * @return  the value of SKF_GEAR.GEAR_MANUFACTURE
	 * @mbg.generated  Fri Jun 15 17:32:09 CST 2018
	 */
	public String getManufacture() {
		return manufacture;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKF_GEAR.GEAR_MANUFACTURE
	 * @param manufacture  the value for SKF_GEAR.GEAR_MANUFACTURE
	 * @mbg.generated  Fri Jun 15 17:32:09 CST 2018
	 */
	public void setManufacture(String manufacture) {
		this.manufacture = manufacture;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKF_GEAR.GEAR_DESCRIPTION
	 * @return  the value of SKF_GEAR.GEAR_DESCRIPTION
	 * @mbg.generated  Fri Jun 15 17:32:09 CST 2018
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKF_GEAR.GEAR_DESCRIPTION
	 * @param description  the value for SKF_GEAR.GEAR_DESCRIPTION
	 * @mbg.generated  Fri Jun 15 17:32:09 CST 2018
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKF_GEAR.GEAR_MESHING_FREQUENCY
	 * @return  the value of SKF_GEAR.GEAR_MESHING_FREQUENCY
	 * @mbg.generated  Fri Jun 15 17:32:09 CST 2018
	 */
	public Float getMeshingFrequency() {
		return meshingFrequency;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKF_GEAR.GEAR_MESHING_FREQUENCY
	 * @param meshingFrequency  the value for SKF_GEAR.GEAR_MESHING_FREQUENCY
	 * @mbg.generated  Fri Jun 15 17:32:09 CST 2018
	 */
	public void setMeshingFrequency(Float meshingFrequency) {
		this.meshingFrequency = meshingFrequency;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKF_GEAR.GEAR_IMAGE_CODE
	 * @return  the value of SKF_GEAR.GEAR_IMAGE_CODE
	 * @mbg.generated  Fri Jun 15 17:32:09 CST 2018
	 */
	public String getImageCode() {
		return imageCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKF_GEAR.GEAR_IMAGE_CODE
	 * @param imageCode  the value for SKF_GEAR.GEAR_IMAGE_CODE
	 * @mbg.generated  Fri Jun 15 17:32:09 CST 2018
	 */
	public void setImageCode(String imageCode) {
		this.imageCode = imageCode;
	}
}