package com.skf.management.model;

public class ImageModel {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKF_IMG.IMG_CODE
	 * @mbg.generated  Tue Jun 05 16:50:42 CST 2018
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKF_IMG.IMG_CPCT_ID
	 * @mbg.generated  Tue Jun 05 16:50:42 CST 2018
	 */
	private Integer componentTypeID;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKF_IMG.IMG_DATA
	 * @mbg.generated  Tue Jun 05 16:50:42 CST 2018
	 */
	private String data;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKF_IMG.IMG_CODE
	 * @return  the value of SKF_IMG.IMG_CODE
	 * @mbg.generated  Tue Jun 05 16:50:42 CST 2018
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKF_IMG.IMG_CODE
	 * @param code  the value for SKF_IMG.IMG_CODE
	 * @mbg.generated  Tue Jun 05 16:50:42 CST 2018
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKF_IMG.IMG_CPCT_ID
	 * @return  the value of SKF_IMG.IMG_CPCT_ID
	 * @mbg.generated  Tue Jun 05 16:50:42 CST 2018
	 */
	public Integer getComponentTypeID() {
		return componentTypeID;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKF_IMG.IMG_CPCT_ID
	 * @param componentTypeID  the value for SKF_IMG.IMG_CPCT_ID
	 * @mbg.generated  Tue Jun 05 16:50:42 CST 2018
	 */
	public void setComponentTypeID(Integer componentTypeID) {
		this.componentTypeID = componentTypeID;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKF_IMG.IMG_DATA
	 * @return  the value of SKF_IMG.IMG_DATA
	 * @mbg.generated  Tue Jun 05 16:50:42 CST 2018
	 */
	public String getData() {
		return data;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKF_IMG.IMG_DATA
	 * @param data  the value for SKF_IMG.IMG_DATA
	 * @mbg.generated  Tue Jun 05 16:50:42 CST 2018
	 */
	public void setData(String data) {
		this.data = data;
	}
}