package com.skf.management.model;

import java.util.Date;

public class NodeModel {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Node.IDNode
	 * @mbg.generated  Mon Jun 11 17:10:37 CST 2018
	 */
	private Integer nodeID;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Node.IDParent
	 * @mbg.generated  Mon Jun 11 17:10:37 CST 2018
	 */
	private Integer nodeParent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Node.IDRefNode
	 * @mbg.generated  Mon Jun 11 17:10:37 CST 2018
	 */
	private Integer idrefnode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Node.TreeType
	 * @mbg.generated  Mon Jun 11 17:10:37 CST 2018
	 */
	private Short treetype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Node.NodeType
	 * @mbg.generated  Mon Jun 11 17:10:37 CST 2018
	 */
	private Short nodetype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Node.NodeStatus
	 * @mbg.generated  Mon Jun 11 17:10:37 CST 2018
	 */
	private Integer nodestatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Node.SortOrderId
	 * @mbg.generated  Mon Jun 11 17:10:37 CST 2018
	 */
	private Integer sortorderid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Node.NodeActive
	 * @mbg.generated  Mon Jun 11 17:10:37 CST 2018
	 */
	private Byte nodeactive;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Node.LastUpdated
	 * @mbg.generated  Mon Jun 11 17:10:37 CST 2018
	 */
	private Date lastupdated;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Node.StatusChanged
	 * @mbg.generated  Mon Jun 11 17:10:37 CST 2018
	 */
	private Date statuschanged;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Node.NodeTag
	 * @mbg.generated  Mon Jun 11 17:10:37 CST 2018
	 */
	private Integer nodetag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Node.NodeConfigurationLock
	 * @mbg.generated  Mon Jun 11 17:10:37 CST 2018
	 */
	private Byte nodeconfigurationlock;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Node.IDNode
	 * @return  the value of dbo.Node.IDNode
	 * @mbg.generated  Mon Jun 11 17:10:37 CST 2018
	 */
	public Integer getNodeID() {
		return nodeID;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Node.IDNode
	 * @param nodeID  the value for dbo.Node.IDNode
	 * @mbg.generated  Mon Jun 11 17:10:37 CST 2018
	 */
	public void setNodeID(Integer nodeID) {
		this.nodeID = nodeID;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Node.IDParent
	 * @return  the value of dbo.Node.IDParent
	 * @mbg.generated  Mon Jun 11 17:10:37 CST 2018
	 */
	public Integer getNodeParent() {
		return nodeParent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Node.IDParent
	 * @param nodeParent  the value for dbo.Node.IDParent
	 * @mbg.generated  Mon Jun 11 17:10:37 CST 2018
	 */
	public void setNodeParent(Integer nodeParent) {
		this.nodeParent = nodeParent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Node.IDRefNode
	 * @return  the value of dbo.Node.IDRefNode
	 * @mbg.generated  Mon Jun 11 17:10:37 CST 2018
	 */
	public Integer getIdrefnode() {
		return idrefnode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Node.IDRefNode
	 * @param idrefnode  the value for dbo.Node.IDRefNode
	 * @mbg.generated  Mon Jun 11 17:10:37 CST 2018
	 */
	public void setIdrefnode(Integer idrefnode) {
		this.idrefnode = idrefnode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Node.TreeType
	 * @return  the value of dbo.Node.TreeType
	 * @mbg.generated  Mon Jun 11 17:10:37 CST 2018
	 */
	public Short getTreetype() {
		return treetype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Node.TreeType
	 * @param treetype  the value for dbo.Node.TreeType
	 * @mbg.generated  Mon Jun 11 17:10:37 CST 2018
	 */
	public void setTreetype(Short treetype) {
		this.treetype = treetype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Node.NodeType
	 * @return  the value of dbo.Node.NodeType
	 * @mbg.generated  Mon Jun 11 17:10:37 CST 2018
	 */
	public Short getNodetype() {
		return nodetype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Node.NodeType
	 * @param nodetype  the value for dbo.Node.NodeType
	 * @mbg.generated  Mon Jun 11 17:10:37 CST 2018
	 */
	public void setNodetype(Short nodetype) {
		this.nodetype = nodetype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Node.NodeStatus
	 * @return  the value of dbo.Node.NodeStatus
	 * @mbg.generated  Mon Jun 11 17:10:37 CST 2018
	 */
	public Integer getNodestatus() {
		return nodestatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Node.NodeStatus
	 * @param nodestatus  the value for dbo.Node.NodeStatus
	 * @mbg.generated  Mon Jun 11 17:10:37 CST 2018
	 */
	public void setNodestatus(Integer nodestatus) {
		this.nodestatus = nodestatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Node.SortOrderId
	 * @return  the value of dbo.Node.SortOrderId
	 * @mbg.generated  Mon Jun 11 17:10:37 CST 2018
	 */
	public Integer getSortorderid() {
		return sortorderid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Node.SortOrderId
	 * @param sortorderid  the value for dbo.Node.SortOrderId
	 * @mbg.generated  Mon Jun 11 17:10:37 CST 2018
	 */
	public void setSortorderid(Integer sortorderid) {
		this.sortorderid = sortorderid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Node.NodeActive
	 * @return  the value of dbo.Node.NodeActive
	 * @mbg.generated  Mon Jun 11 17:10:37 CST 2018
	 */
	public Byte getNodeactive() {
		return nodeactive;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Node.NodeActive
	 * @param nodeactive  the value for dbo.Node.NodeActive
	 * @mbg.generated  Mon Jun 11 17:10:37 CST 2018
	 */
	public void setNodeactive(Byte nodeactive) {
		this.nodeactive = nodeactive;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Node.LastUpdated
	 * @return  the value of dbo.Node.LastUpdated
	 * @mbg.generated  Mon Jun 11 17:10:37 CST 2018
	 */
	public Date getLastupdated() {
		return lastupdated;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Node.LastUpdated
	 * @param lastupdated  the value for dbo.Node.LastUpdated
	 * @mbg.generated  Mon Jun 11 17:10:37 CST 2018
	 */
	public void setLastupdated(Date lastupdated) {
		this.lastupdated = lastupdated;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Node.StatusChanged
	 * @return  the value of dbo.Node.StatusChanged
	 * @mbg.generated  Mon Jun 11 17:10:37 CST 2018
	 */
	public Date getStatuschanged() {
		return statuschanged;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Node.StatusChanged
	 * @param statuschanged  the value for dbo.Node.StatusChanged
	 * @mbg.generated  Mon Jun 11 17:10:37 CST 2018
	 */
	public void setStatuschanged(Date statuschanged) {
		this.statuschanged = statuschanged;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Node.NodeTag
	 * @return  the value of dbo.Node.NodeTag
	 * @mbg.generated  Mon Jun 11 17:10:37 CST 2018
	 */
	public Integer getNodetag() {
		return nodetag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Node.NodeTag
	 * @param nodetag  the value for dbo.Node.NodeTag
	 * @mbg.generated  Mon Jun 11 17:10:37 CST 2018
	 */
	public void setNodetag(Integer nodetag) {
		this.nodetag = nodetag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Node.NodeConfigurationLock
	 * @return  the value of dbo.Node.NodeConfigurationLock
	 * @mbg.generated  Mon Jun 11 17:10:37 CST 2018
	 */
	public Byte getNodeconfigurationlock() {
		return nodeconfigurationlock;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Node.NodeConfigurationLock
	 * @param nodeconfigurationlock  the value for dbo.Node.NodeConfigurationLock
	 * @mbg.generated  Mon Jun 11 17:10:37 CST 2018
	 */
	public void setNodeconfigurationlock(Byte nodeconfigurationlock) {
		this.nodeconfigurationlock = nodeconfigurationlock;
	}
}