package com.skf.management.model;

public class OEMModel {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKF_OEM.OEM_CODE
	 * @mbg.generated  Thu May 31 18:00:54 CST 2018
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKF_OEM.OEM_NAME
	 * @mbg.generated  Thu May 31 18:00:54 CST 2018
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKF_OEM.OEM_COUNTRY
	 * @mbg.generated  Thu May 31 18:00:54 CST 2018
	 */
	private String country;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKF_OEM.OEM_STATE
	 * @mbg.generated  Thu May 31 18:00:54 CST 2018
	 */
	private String state;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKF_OEM.OEM_CITY
	 * @mbg.generated  Thu May 31 18:00:54 CST 2018
	 */
	private String city;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKF_OEM.OEM_ADDRESS
	 * @mbg.generated  Thu May 31 18:00:54 CST 2018
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKF_OEM.OEM_URL
	 * @mbg.generated  Thu May 31 18:00:54 CST 2018
	 */
	private String url;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKF_OEM.OEM_INTRODUCTION
	 * @mbg.generated  Thu May 31 18:00:54 CST 2018
	 */
	private String introduction;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKF_OEM.OEM_IMG
	 * @mbg.generated  Thu May 31 18:00:54 CST 2018
	 */
	private String img;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKF_OEM.OEM_CODE
	 * @return  the value of SKF_OEM.OEM_CODE
	 * @mbg.generated  Thu May 31 18:00:54 CST 2018
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKF_OEM.OEM_CODE
	 * @param code  the value for SKF_OEM.OEM_CODE
	 * @mbg.generated  Thu May 31 18:00:54 CST 2018
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKF_OEM.OEM_NAME
	 * @return  the value of SKF_OEM.OEM_NAME
	 * @mbg.generated  Thu May 31 18:00:54 CST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKF_OEM.OEM_NAME
	 * @param name  the value for SKF_OEM.OEM_NAME
	 * @mbg.generated  Thu May 31 18:00:54 CST 2018
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKF_OEM.OEM_COUNTRY
	 * @return  the value of SKF_OEM.OEM_COUNTRY
	 * @mbg.generated  Thu May 31 18:00:54 CST 2018
	 */
	public String getCountry() {
		return country;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKF_OEM.OEM_COUNTRY
	 * @param country  the value for SKF_OEM.OEM_COUNTRY
	 * @mbg.generated  Thu May 31 18:00:54 CST 2018
	 */
	public void setCountry(String country) {
		this.country = country;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKF_OEM.OEM_STATE
	 * @return  the value of SKF_OEM.OEM_STATE
	 * @mbg.generated  Thu May 31 18:00:54 CST 2018
	 */
	public String getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKF_OEM.OEM_STATE
	 * @param state  the value for SKF_OEM.OEM_STATE
	 * @mbg.generated  Thu May 31 18:00:54 CST 2018
	 */
	public void setState(String state) {
		this.state = state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKF_OEM.OEM_CITY
	 * @return  the value of SKF_OEM.OEM_CITY
	 * @mbg.generated  Thu May 31 18:00:54 CST 2018
	 */
	public String getCity() {
		return city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKF_OEM.OEM_CITY
	 * @param city  the value for SKF_OEM.OEM_CITY
	 * @mbg.generated  Thu May 31 18:00:54 CST 2018
	 */
	public void setCity(String city) {
		this.city = city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKF_OEM.OEM_ADDRESS
	 * @return  the value of SKF_OEM.OEM_ADDRESS
	 * @mbg.generated  Thu May 31 18:00:54 CST 2018
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKF_OEM.OEM_ADDRESS
	 * @param address  the value for SKF_OEM.OEM_ADDRESS
	 * @mbg.generated  Thu May 31 18:00:54 CST 2018
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKF_OEM.OEM_URL
	 * @return  the value of SKF_OEM.OEM_URL
	 * @mbg.generated  Thu May 31 18:00:54 CST 2018
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKF_OEM.OEM_URL
	 * @param url  the value for SKF_OEM.OEM_URL
	 * @mbg.generated  Thu May 31 18:00:54 CST 2018
	 */
	public void setUrl(String url) {
		this.url = url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKF_OEM.OEM_INTRODUCTION
	 * @return  the value of SKF_OEM.OEM_INTRODUCTION
	 * @mbg.generated  Thu May 31 18:00:54 CST 2018
	 */
	public String getIntroduction() {
		return introduction;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKF_OEM.OEM_INTRODUCTION
	 * @param introduction  the value for SKF_OEM.OEM_INTRODUCTION
	 * @mbg.generated  Thu May 31 18:00:54 CST 2018
	 */
	public void setIntroduction(String introduction) {
		this.introduction = introduction;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKF_OEM.OEM_IMG
	 * @return  the value of SKF_OEM.OEM_IMG
	 * @mbg.generated  Thu May 31 18:00:54 CST 2018
	 */
	public String getImg() {
		return img;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKF_OEM.OEM_IMG
	 * @param img  the value for SKF_OEM.OEM_IMG
	 * @mbg.generated  Thu May 31 18:00:54 CST 2018
	 */
	public void setImg(String img) {
		this.img = img;
	}
}