package com.skf.management.model;

import java.util.Date;

public class ScoreModel {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf_cmpt_score.CMPT_CODE
	 * @mbg.generated  Fri Jun 15 17:49:01 CST 2018
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf_cmpt_score.TIME
	 * @mbg.generated  Fri Jun 15 17:49:01 CST 2018
	 */
	private Date time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf_cmpt_score.CALSS
	 * @mbg.generated  Fri Jun 15 17:49:01 CST 2018
	 */
	private String calss;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf_cmpt_score.SCORE
	 * @mbg.generated  Fri Jun 15 17:49:01 CST 2018
	 */
	private Float score;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf_cmpt_score.TOTAL_VALUE
	 * @mbg.generated  Fri Jun 15 17:49:01 CST 2018
	 */
	private Float totalValue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf_cmpt_score.DANGER_LEVEL
	 * @mbg.generated  Fri Jun 15 17:49:01 CST 2018
	 */
	private Float dangerLevel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf_cmpt_score.BP_TYPE
	 * @mbg.generated  Fri Jun 15 17:49:01 CST 2018
	 */
	private String bpType;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf_cmpt_score.CMPT_CODE
	 * @return  the value of skf_cmpt_score.CMPT_CODE
	 * @mbg.generated  Fri Jun 15 17:49:01 CST 2018
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf_cmpt_score.CMPT_CODE
	 * @param code  the value for skf_cmpt_score.CMPT_CODE
	 * @mbg.generated  Fri Jun 15 17:49:01 CST 2018
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf_cmpt_score.TIME
	 * @return  the value of skf_cmpt_score.TIME
	 * @mbg.generated  Fri Jun 15 17:49:01 CST 2018
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf_cmpt_score.TIME
	 * @param time  the value for skf_cmpt_score.TIME
	 * @mbg.generated  Fri Jun 15 17:49:01 CST 2018
	 */
	public void setTime(Date time) {
		this.time = time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf_cmpt_score.CALSS
	 * @return  the value of skf_cmpt_score.CALSS
	 * @mbg.generated  Fri Jun 15 17:49:01 CST 2018
	 */
	public String getCalss() {
		return calss;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf_cmpt_score.CALSS
	 * @param calss  the value for skf_cmpt_score.CALSS
	 * @mbg.generated  Fri Jun 15 17:49:01 CST 2018
	 */
	public void setCalss(String calss) {
		this.calss = calss;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf_cmpt_score.SCORE
	 * @return  the value of skf_cmpt_score.SCORE
	 * @mbg.generated  Fri Jun 15 17:49:01 CST 2018
	 */
	public Float getScore() {
		return score;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf_cmpt_score.SCORE
	 * @param score  the value for skf_cmpt_score.SCORE
	 * @mbg.generated  Fri Jun 15 17:49:01 CST 2018
	 */
	public void setScore(Float score) {
		this.score = score;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf_cmpt_score.TOTAL_VALUE
	 * @return  the value of skf_cmpt_score.TOTAL_VALUE
	 * @mbg.generated  Fri Jun 15 17:49:01 CST 2018
	 */
	public Float getTotalValue() {
		return totalValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf_cmpt_score.TOTAL_VALUE
	 * @param totalValue  the value for skf_cmpt_score.TOTAL_VALUE
	 * @mbg.generated  Fri Jun 15 17:49:01 CST 2018
	 */
	public void setTotalValue(Float totalValue) {
		this.totalValue = totalValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf_cmpt_score.DANGER_LEVEL
	 * @return  the value of skf_cmpt_score.DANGER_LEVEL
	 * @mbg.generated  Fri Jun 15 17:49:01 CST 2018
	 */
	public Float getDangerLevel() {
		return dangerLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf_cmpt_score.DANGER_LEVEL
	 * @param dangerLevel  the value for skf_cmpt_score.DANGER_LEVEL
	 * @mbg.generated  Fri Jun 15 17:49:01 CST 2018
	 */
	public void setDangerLevel(Float dangerLevel) {
		this.dangerLevel = dangerLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf_cmpt_score.BP_TYPE
	 * @return  the value of skf_cmpt_score.BP_TYPE
	 * @mbg.generated  Fri Jun 15 17:49:01 CST 2018
	 */
	public String getBpType() {
		return bpType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf_cmpt_score.BP_TYPE
	 * @param bpType  the value for skf_cmpt_score.BP_TYPE
	 * @mbg.generated  Fri Jun 15 17:49:01 CST 2018
	 */
	public void setBpType(String bpType) {
		this.bpType = bpType;
	}
}