package com.skf.management.model;

public class SensorModel {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKF_SNSR.SNSR_CODE
	 * @mbg.generated  Fri Jun 15 18:04:35 CST 2018
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKF_SNSR.SNSR_QPMT_CODE
	 * @mbg.generated  Fri Jun 15 18:04:35 CST 2018
	 */
	private String equipmentCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKF_SNSR.SNSR_NAME
	 * @mbg.generated  Fri Jun 15 18:04:35 CST 2018
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKF_SNSR.SNSR_ANGLE
	 * @mbg.generated  Fri Jun 15 18:04:35 CST 2018
	 */
	private Float angle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKF_SNSR.SNSR_POS_X
	 * @mbg.generated  Fri Jun 15 18:04:35 CST 2018
	 */
	private Float posX;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKF_SNSR.SNSR_POS_Y
	 * @mbg.generated  Fri Jun 15 18:04:35 CST 2018
	 */
	private Float posY;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKF_SNSR.SNSR_SCHEMA_NAME
	 * @mbg.generated  Fri Jun 15 18:04:35 CST 2018
	 */
	private String schemaName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKF_SNSR.SNSR_NODE_ID
	 * @mbg.generated  Fri Jun 15 18:04:35 CST 2018
	 */
	private Integer nodeID;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKF_SNSR.SNSR_CODE
	 * @return  the value of SKF_SNSR.SNSR_CODE
	 * @mbg.generated  Fri Jun 15 18:04:35 CST 2018
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKF_SNSR.SNSR_CODE
	 * @param code  the value for SKF_SNSR.SNSR_CODE
	 * @mbg.generated  Fri Jun 15 18:04:35 CST 2018
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKF_SNSR.SNSR_QPMT_CODE
	 * @return  the value of SKF_SNSR.SNSR_QPMT_CODE
	 * @mbg.generated  Fri Jun 15 18:04:35 CST 2018
	 */
	public String getEquipmentCode() {
		return equipmentCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKF_SNSR.SNSR_QPMT_CODE
	 * @param equipmentCode  the value for SKF_SNSR.SNSR_QPMT_CODE
	 * @mbg.generated  Fri Jun 15 18:04:35 CST 2018
	 */
	public void setEquipmentCode(String equipmentCode) {
		this.equipmentCode = equipmentCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKF_SNSR.SNSR_NAME
	 * @return  the value of SKF_SNSR.SNSR_NAME
	 * @mbg.generated  Fri Jun 15 18:04:35 CST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKF_SNSR.SNSR_NAME
	 * @param name  the value for SKF_SNSR.SNSR_NAME
	 * @mbg.generated  Fri Jun 15 18:04:35 CST 2018
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKF_SNSR.SNSR_ANGLE
	 * @return  the value of SKF_SNSR.SNSR_ANGLE
	 * @mbg.generated  Fri Jun 15 18:04:35 CST 2018
	 */
	public Float getAngle() {
		return angle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKF_SNSR.SNSR_ANGLE
	 * @param angle  the value for SKF_SNSR.SNSR_ANGLE
	 * @mbg.generated  Fri Jun 15 18:04:35 CST 2018
	 */
	public void setAngle(Float angle) {
		this.angle = angle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKF_SNSR.SNSR_POS_X
	 * @return  the value of SKF_SNSR.SNSR_POS_X
	 * @mbg.generated  Fri Jun 15 18:04:35 CST 2018
	 */
	public Float getPosX() {
		return posX;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKF_SNSR.SNSR_POS_X
	 * @param posX  the value for SKF_SNSR.SNSR_POS_X
	 * @mbg.generated  Fri Jun 15 18:04:35 CST 2018
	 */
	public void setPosX(Float posX) {
		this.posX = posX;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKF_SNSR.SNSR_POS_Y
	 * @return  the value of SKF_SNSR.SNSR_POS_Y
	 * @mbg.generated  Fri Jun 15 18:04:35 CST 2018
	 */
	public Float getPosY() {
		return posY;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKF_SNSR.SNSR_POS_Y
	 * @param posY  the value for SKF_SNSR.SNSR_POS_Y
	 * @mbg.generated  Fri Jun 15 18:04:35 CST 2018
	 */
	public void setPosY(Float posY) {
		this.posY = posY;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKF_SNSR.SNSR_SCHEMA_NAME
	 * @return  the value of SKF_SNSR.SNSR_SCHEMA_NAME
	 * @mbg.generated  Fri Jun 15 18:04:35 CST 2018
	 */
	public String getSchemaName() {
		return schemaName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKF_SNSR.SNSR_SCHEMA_NAME
	 * @param schemaName  the value for SKF_SNSR.SNSR_SCHEMA_NAME
	 * @mbg.generated  Fri Jun 15 18:04:35 CST 2018
	 */
	public void setSchemaName(String schemaName) {
		this.schemaName = schemaName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKF_SNSR.SNSR_NODE_ID
	 * @return  the value of SKF_SNSR.SNSR_NODE_ID
	 * @mbg.generated  Fri Jun 15 18:04:35 CST 2018
	 */
	public Integer getNodeID() {
		return nodeID;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKF_SNSR.SNSR_NODE_ID
	 * @param nodeID  the value for SKF_SNSR.SNSR_NODE_ID
	 * @mbg.generated  Fri Jun 15 18:04:35 CST 2018
	 */
	public void setNodeID(Integer nodeID) {
		this.nodeID = nodeID;
	}
}