package com.skf.management.model;

public class UserCustomerModelKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf_usr_cstm.USR_CODE
	 * @mbg.generated  Thu May 31 17:15:42 CST 2018
	 */
	private String userCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column skf_usr_cstm.CSTM_CODE
	 * @mbg.generated  Thu May 31 17:15:42 CST 2018
	 */
	private String customerCode;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf_usr_cstm.USR_CODE
	 * @return  the value of skf_usr_cstm.USR_CODE
	 * @mbg.generated  Thu May 31 17:15:42 CST 2018
	 */
	public String getUserCode() {
		return userCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf_usr_cstm.USR_CODE
	 * @param userCode  the value for skf_usr_cstm.USR_CODE
	 * @mbg.generated  Thu May 31 17:15:42 CST 2018
	 */
	public void setUserCode(String userCode) {
		this.userCode = userCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column skf_usr_cstm.CSTM_CODE
	 * @return  the value of skf_usr_cstm.CSTM_CODE
	 * @mbg.generated  Thu May 31 17:15:42 CST 2018
	 */
	public String getCustomerCode() {
		return customerCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column skf_usr_cstm.CSTM_CODE
	 * @param customerCode  the value for skf_usr_cstm.CSTM_CODE
	 * @mbg.generated  Thu May 31 17:15:42 CST 2018
	 */
	public void setCustomerCode(String customerCode) {
		this.customerCode = customerCode;
	}
}